### ISSUE TITLE
Gtk.EventBox suspected of misbehaving in NsCDE's GTK theme

### ISSUE THREAD

**Issue by 97-109-107** [NsCDE/NsCDE#102]
Hi & again thanks for your great work!

I've stumbled upon an issue with, as far I understand, the GTK theme generated by NsCDE.

### Issue
When using NsCDE a `Gtk.EventBox` element appears empty, missing or transparent. This has been observed when  using [mpdevil](https://github.com/SoongNoonien/mpdevil/). I don't believe I've seen this happen with any other software I use, but I might've overlooked it.

I've discussed this with the author of that software, he led me towards investigation GTK - issue [here](https://github.com/SoongNoonien/mpdevil/issues/52) 

### Pictures 

_see top-right box_

![a](https://user-images.githubusercontent.com/1902438/171280841-594e347e-ace9-48fc-8e45-f5c9a4f9a14f.png "a")

![b](https://user-images.githubusercontent.com/1902438/172200578-b6b71fbe-b5c1-40d5-8b84-09216e67962f.png "b")

**Comment by 97-109-107** [comment]
Thank, this quick fix works; 
Do you want me to close this issue?

**Comment by NsCDE** [comment]
Hi @97-109-107

No, leave it opened please. It is stil the issue.

**Comment by NsCDE** [comment]
Carefully workarounded and basically fixed in main branch.

**Comment by NsCDE** [comment]
No, leave it open please. It is still not settled.

-------- Original Message --------
