### ISSUE TITLE
pkill -o is not supported on NetBSD

### ISSUE THREAD

**Issue by drscream** [NsCDE/NsCDE#103]
Sadly `pkill -o` is not supported on NetBSD (-current). Which is used in the following configuration file: https://github.com/NsCDE/NsCDE/blob/master/data/fvwm/Functions.fvwmconf.in#L1296

I would only like to report it so it will be not forgotten at some point in time. Maybe you already know a good workaround otherwise it would be also nice if NetBSD `pkill` would support the `-o` option.

**Comment by NsCDE** [comment]
Thanks for reporting this. I wassn't aware of this. It was probably missed on testing VMs. I will see what I can do here.

**Comment by NsCDE** [comment]
f_PolkitAgent has been reorganized to work differently, hence no more need to select old process, which is not supported by NetBSD and maybe some other systems pkill/pgrep commands.
