### ISSUE TITLE
Question: cpu and disk overview in frontpanel 

### ISSUE THREAD

**Issue by drscream** [NsCDE/NsCDE#104]
As you might already know my question from the title: I'm looking for a solution to add the cpu and disk overview to the FrontPanel as it was part of the Solaris CDE version. Basically I would like to use the idea of showing cpu and disk to also show the battery status.

![Solaris CDE FrontPanel](https://user-images.githubusercontent.com/315645/175951213-cb12b384-fa0b-47f7-9e2d-15159fe7bd65.png)

At the moment of writing I'm not sure how easy it is to provide a more dynamic FrontPanel. But if you would guide me to the correct location I would look into that myself.

**Comment by drscream** [comment]
I already found https://github.com/NsCDE/NsCDE/issues/93 which shows how that it's possible to add a WindowMaker widget. But if I try to add it somehow it does not stay on top and I need to specify the location of the widget. I thought it might be possible to embed it somehow like the clock.

**Comment by drscream** [comment]
Hi @NsCDE

thanks for taking the time to answer my more complicated question. I also noticed that somehow `sdtperfmeter` is not really available so I tried to add an WindowMaker applet to the Front Panel. For that I wasn't 100% sure what is the correct file in NsCDE which I need to modify because there is `FrontPanel.fvwm3.fvwmconf` and `FrontPanel.actions`.

After I found the solution to add an WindowMaker applet to the correct position I realised that if the mouse focus moves to the Front Panel the applet disappear (because it's in the back of the Front Panel). This was easily solved by adding the correct entries to `.NsCDE/Style.fvwmlocal`:

```
Style "wmbattery" NoTitle, Sticky, StaysOnTop, !FPGrabFocus, SkipMapping, WindowListSkip, NeverFocus
```

I think all in all this solved my issue, so the WindowMaker applet is not really part of the FrontPanel but stays on the top of an empty FrontPanel Button.

**Comment by drscream** [comment]
Thanks a lot, that works well for `Btn10`, but if I try the same for `Btn8` it will not work. Is this something special?

**Comment by NsCDE** [comment]
Hi @drscream

Congratulations. You discovered a bug. new fpseticon is in master tree commited now.

Button 8 is by default indeed special: it will act and show icon of the file manager only if that file manager is known to be able to act as application manager, if not, it will show editor command and call default editor. If customized by the user, it will not be special case, but this worked for normal icons, and it was missing recongnition of the applet. This is now fixed.

**Comment by drscream** [comment]
I can confirm your fix works well! Thanks a lot for the details and for fixing the `Btn8`-bug. I would consider this question and so problem resolved.

Thanks again for all your work!
