### ISSUE TITLE
Consider /usr/bin/env python3 shebang

### ISSUE THREAD

**Issue by drscream** [NsCDE/NsCDE#105]
Because of an [issue](http://gnats.netbsd.org/cgi-bin/query-pr-single.pl?number=51152) in NetBSD `pkg_alternative` wrapper `/usr/pkg/bin/python3` result in an shell call if used as shebang the python3 scripts doesn't work correctly on NetBSD.

But if you consider switching from `#!/usr/pkg/bin/python3` to `#!/usr/bin/env python3` it would work. I know this is basically a bug in NetBSD and not fully related to NsCDE - but maybe switching to `#!/usr/bin/env python3` provide additional benefits?

**Comment by NsCDE** [comment]
Hi @drscream

On my VM with NetBSD, python3 is /usr/bin/python3 and it is not a wrapper, but binary itself. "#!/usr/bin/env python3" has been used in NsCDE 1.X, but since 2.X and autoconf/automake based installation/adaptation, this is no longer the case.

Try to put as first in $PATH path where real python3 binary is installed and then run ./configure. This should produce shebang that is calling python3 directly.

**Comment by drscream** [comment]
Would you be able to provide additional insides of your NetBSD virtual machine? Which packages are you using to install `python3`? As I know normally most pkgsrc packages should use `/usr/pkg` as prefix and use the `pkg_alternative` wrapper?

**Comment by drscream** [comment]
Could you check for `/usr/pkg/bin/python3` (or `/usr/pkg/bin/python`) please?

**Comment by NsCDE** [comment]
This doesn't exist on my NetBSD system. OTOH, I don't have pkg_alternative, so maybe this is the case. Try to create symlink directly on binary and make ./configure.

**Comment by drscream** [comment]
That works for sure. It also works if I specify the binary directly and not the wrapper script. But I considered that most people using `pkgsrc` with binary packages (for example from https://pkgsrc.joyent.com) ending up using the `pkg_alternative` wrapper.

**Comment by NsCDE** [comment]
This is erroneous behaviour of the system itself combined with bad package/alternatives  decisions. Unfortunately, systems with smaller user base tends to have also smaller maintainer base, which means less effort/time, less decision makers, which in turn can lead to such problems.
IMHO, those who use such systems are probably expected to deal with hacks and such issues in a ways not expected by users of, for example, Ubuntu, Mint, Fedora etc ...

**Comment by drscream** [comment]
As mentioned it's a bug in `pkg_alternatives` which are already addressed - and hopefully solved in the future.

I only considered it might face other people as well and found out that using `#!/usr/bin/env` or the full path to the python version worked well. Maybe it's something for the FAQ to mention?

**Comment by NsCDE** [comment]
Hi @drscream 

Ok, here is the option to override broken alternatives for Python 3.

  --with-python-shebang="STRING"
                          How to call Python 3 in python scripts (specified
                          WITHOUT hash and exclamation mark). This disables
                          python 3 autodetection and fully trusts what is
                          provided by the user. One example of this option can
                          be: "/usr/bin/env python3".

This will be soon in 2.2.
