### ISSUE TITLE
Wayland support?

### ISSUE THREAD

**Issue by volkertb** [NsCDE/NsCDE#107]
Hi! :)

I learned about this project through [Phoronix](https://www.phoronix.com/news/NsCDE-2.2-Desktop-Released).

Congrats with the 2.2 release! Love the retro look. Throws me back to those UNIX terminals that we used to have in the computer lab back in my college days.

Anyway, I was surprised that a search for "Wayland" turned up zero results in the GitHub issues for this project. Am I really the first person to ask this?

As you know, X11 is not really being developed further and all new desktop UI development in open-source POSIX land is going on in Wayland these days. Are there any plans to add (native) Wayland support to NsCDE as well? If not, why not?

Thanks.

**Comment by NsCDE** [comment]
Hi @volkertb 

NsCDE is highly dependent on FVWM. While there is no wayland works on FVWM, NsCDE is X11 only for the time beeing. FVWM developers will decide if it is worth and when to consider wayland.

**Comment by blacklightpy** [comment]
Hi @NsCDE, FVWM developer isn't going to move to Wayland apparently (https://github.com/fvwmorg/fvwm3/issues/970).

Is it not possible to do this otherwise?

I guess not, since NsCDE is an FVWM wrapper.

**Comment by Alerymin** [comment]
The best option would be switching to another WM, probably windowmaker so there is compatibility with the wayland alternative wlmaker. Or maybe Openbox/labwc
