### ISSUE TITLE
"suse rpms"???

### ISSUE THREAD

**Issue by lemmy04** [NsCDE/NsCDE#108]
Those "suse rpms" that can be found here - where have they been built, and for **which** suse version?
SLES? SLED? Leat 15.3 or 15.4? Tumbleweed?

**Comment by NsCDE** [comment]
Hi @lemmy04 

Tumbleweed for binary RPM. You can rebuild for any other Suse or Fedora with rpmbuild --rebuild <src.rpm file>. Or you can do it directly from the tarball with `rpmbuild -tb NsCDE-2.2.tar.gz`. Of course, build tools and dependencies must be in place on the system prior to this.
