### ISSUE TITLE
Unsigned RPM packages

### ISSUE THREAD

**Issue by lemmy04** [NsCDE/NsCDE#109]
Trying to install the suse rpm, zypper refuses because the package is not signed.

**Comment by NsCDE** [comment]
Hi @lemmy04

You are right. Even if this packages are built as an convenience on my test VMs where I test and develop NsCDE, I should probably sign them. But while you are downloading directly from github, and https, you are fine ... or you can rebuild them yourself.

Install directly with rpm. For example: `rpm -ivh <name of the package.rpm>`. As I see in zypper(8) man page, you can use option `--allow-unsigned-rpm`.
