### ISSUE TITLE
Dependencies update for Debian/Ubuntu/Mint

### ISSUE THREAD

**Issue by HankG** [NsCDE/NsCDE#110]
I just tried installing this with the standard instructions and ran into a problem of missing dependencies. I was able to tweak the dependencies list under Mint 20 to get this working. Since I haven't tested this across several distros I didn't want to do a PR. I did want to capture the changes however. Also since I used git I added it to the list of applications at the end.

```bash
sudo apt install -y build-essential ksh x11-utils xdotool imagemagick \
    xscreensaver x11-xserver-utils python3-yaml python3-pyqt5 \
    qt5ct qt5-style-plugins stalonetray xterm python3 \
    python3-xdg libstroke0 xsettingsd fvwm fvwm-icons \
    libx11-dev libxext-dev libxpm-dev libfile-mimeinfo-perl \
    automake gkrellm rofi xclip git
```

**Comment by urnenfeld** [comment]
I just did this morning and ran as well into problems:
I can confirm your additions, checking my history, maybe we could miss **gettext**?

**Comment by NsCDE** [comment]
Hi @HankG and @urnenfeld 

Thanks for this report. Gettext is also needed, yes. I will invastigate, and probably add Mint to the VM to test on it too, among Debian and Ubuntu when we are talking about deb based distros.

**Comment by HankG** [comment]
I confirmed that on Ubuntu 22 gettext needs to be added as well, yup.

**Comment by NsCDE** [comment]
Added in master, it will be default in 2.3.
