### ISSUE TITLE
Display orientation error

### ISSUE THREAD

**Issue by vrodeo** [NsCDE/NsCDE#111]
Hi,
Installed nscde_2.2-6_amd64.deb and got greeted by the following error message when I tried changing the display orientation:

GDBus.Error:org.freeesktop.DBus.Error.ServiceUnkown: The name org.cinnamon.SettingsDaemon.XRANDR_2 was not provided by an .service files

I've tried playing with a couple setting with no avail. Any pointers will be appreciated.

thanks much,
/v

**Comment by NsCDE** [comment]
Hi @vrodeo 

This looks like message from some Cinnamon desktop environment tool which probably requires Cinnamon to work. Use xrandr(1) or arandr GUI tool to change monitor settings.

**Comment by vrodeo** [comment]
Yeah that's what confusing because I had KDE running prior to installing NsCDE. So install arandr package and change the monitor settings from there?

Thanks again,
/v

**Comment by NsCDE** [comment]
Hi @vrodeo

Yes. Try with arandr, or with xrandr  from command line, look for online examples. Notice that NsCDE was not well tested with portrait orientation, but as long as width is 1024 px or more, it should be fine.

**Comment by vrodeo** [comment]
Yup that was it, thanks....I hope NsCDE gets further traction and looking forward to further updates!

thanks for your efforts in resurrecting CDE 

thanks,
/v
