### ISSUE TITLE
How to clear/uninstall window decorations?

### ISSUE THREAD

**Issue by tenox7** [NsCDE/NsCDE#112]
I have removed NsCDE from my system but window decorations persists. I switched to another window manager but now some of my windows have no title bars or CDE looking menus, etc. How do I remove that? Thank you!

**Comment by NsCDE** [comment]
Hi
- Use qt5ct to select another Qt theme
- With other WM tool, or manually, edit ~/.config/gtk-3.0/settings.ini and change the theme
- Same for gtk2 - edit ~/.gtkrc-2.0

For windows having or not having title bars - this is nothing to do with gtk or qt theme, or with fvwm or NsCDE, but with your new wm.

**Comment by NsCDE** [comment]
Hi @tenox7 

Did you managed to change GTK and Qt themes? May we close this issue?

**Comment by tenox7** [comment]
Yes thank you for explanation. My wm is not new but old, I used it before NsCDE, the decorations have been changed for gnome terminal specifically. I cleaned it up and it works now thank you!
