### ISSUE TITLE
tkremind radio button missing dot (selection indicator)

### ISSUE THREAD

**Issue by BenCollver** [NsCDE/NsCDE#114]
When i run tkremind in NsCDE and i click on a radio button, it fails to show the selected radio button.  Instead, ALL radio buttons appear to be unselected (_).

When i run tkremind in XFCE and i click on a radio button, shows the selected radio button as expected (*).

I am using NsCDE 2.2 on Slackware64 15.0.
https://slackbuilds.org/repository/15.0/desktop/NsCDE/

Below is a screenshot from NsCDE:
![nscde](https://user-images.githubusercontent.com/2358705/184677419-d0a490ae-f2a2-475c-8c17-c28d464e61c4.png)

Below is a screenshot from XFCE:
![xfce](https://user-images.githubusercontent.com/2358705/184677495-fc49ef6f-49e3-4a23-a577-1aa1fff3badc.png)

**Comment by NsCDE** [comment]
Hi @BenCollver 

Sorry for waiting, summer vacation ...

I cannot reproduce this under default color scheme "Broica". That is, I see the dot in radio button under NsCDE.

Please give me a more info:

- Color scheme you are using under NsCDE (or paste colors from ~/.NsCDE/palettes/<your>.dp if using custom
- Which version of TCL and TK library?
- Which OS/distro and version?

Wit that data, I will try to reproduce above screenshoted problem locally again, thanks.

**Comment by BenCollver** [comment]
When i use the "Broica" color scheme, it resolves the problem.

The problem happens when i used the "NorthernSky" color scheme.

I am using tcl-8.6.12 and tk-8.6.12

I am using Slackware64 version 15.0

**Comment by NsCDE** [comment]
Thanks, I was able to reproduce this now in VM.

I will take a look into this this days.

**Comment by NsCDE** [comment]
For a quick workaround, you can put

`Tkremind*selectColor: #41a952c85c00`

in ~/.NsCDE/Xdefaults.local and reload X resources:

`xrdb < ~/.NsCDE/Xdefaults.local`

But there is more broken things and behaviours with TCL/TK apps regarding X resources, so I have to fix this for good. Leave issue open.

**Comment by BenCollver** [comment]
Thanks for the workaround!

By the way, this issue also affects the Palemoon and Seamonkey web browsers.  For example, if you browse to https://romhacking.net/ and type text into the search box, the search text is invisible because the font is white on a white background.

**Comment by NsCDE** [comment]
@BenCollver 

I've never tried this two browsers, I will take a look at it in VM. Thanks for reporting.
