### ISSUE TITLE
Some color themes make parts of Firefox unreadable

### ISSUE THREAD

**Issue by jjramsey** [NsCDE/NsCDE#116]
Here's how to trigger the problem:

* Pick certain themes, such as Crimson or Solyaris, or, for a milder case of the problem, the color theme named "FVWM". (There are other themes that have the problem as well.)
* Go to save a bookmark in Firefox. A dialog box will come up and in the "Location" dropdown, pick "Choose...".

The lists of locations will look mostly blank, with white text against a white or very light background. I'm not sure if the problem is with the color theme or with Firefox, or if there are other apps affected.

**Comment by NsCDE** [comment]
Hi @jjramsey 

Please provide me more info:

- Version of Firefox

- Are you using Crimson or Solyaris and in what color mode? 4 colors or 8 colors?

- Are you using NsCDE userChrome.css and userContent.css additions while choosing theme in Color Style Manager (from ~/.NsCDE/libexec/colormgr.local) or not?

**Comment by jjramsey** [comment]
* Firefox version: 91.13.0esr
* I've used both Crimson and Solyaris before, but stopped using them after I found the problem that I described. For both of them, I used the 8-color version.
* I was unaware of either userChrome.css or userContent.css, so if I'm using them, it's by accident.

**Comment by NsCDE** [comment]
Possible explanations are buggy version of GTK 3 library or it's Pixmap engine used by NsCDE gtk3 theme.
