### ISSUE TITLE
A few questions about default keybindings, rofi, and managing displays

### ISSUE THREAD

**Issue by 31PNMR** [NsCDE/NsCDE#118]
Greetings

I'm enjoying the nostalgia of using CDE again, but I'm new to using FVWM. One of the things I'm having trouble with is finding where FVWM ends and NsCDE begins.

There are a few troubling keybindings that I would like to change or disable. For example, `Shift+ArrowKey` changes focus to another window, while I'm used to that selecting text. I also need to be able to switch keyboard layouts. I have been using `Win+Space` to do this in i3/XFCE, but in NsCDE that is bound to the Occupy Workspace dialog. I can't determine if these keybindings are related to FVWM or NsCDE. I `grep`ed the `~/.NsCDE` directory trying to find them, but came up empty.

I really like that rofi is set to match the particular color theme selected, however, the `run` menu is of very little use to me. I tried editing the `config` file created by NsCDE, but this does not seem to affect the modi shown. Is there somewhere else I should look?

I'd like to avoid having to manage my display setups using `xrandr` on the command line. Is there a suggested graphical tool that can be used to manage displays, especially for a laptop?

Thanks again for creating this amazing experience. It's been a lot of fun. I'm trying to get to a point where I can actually daily drive it. I'm currently running Arch Linux. Thank you for any suggestions.

**Comment by NsCDE** [comment]
Hi @31PNMR

NsCDE uses standard FVWM keybinding functions, it is just a choice of organization of default configurations. If you want to override or erase particular key binding, you should be able to do this with:

`Key Up A S -` in your local ~/.NsCDE/Keybindings.fvwmlocal and restart NsCDE

Or in runtime (will not be preserved, see above for permanent config) without restart from the shell/terminal:

`$ nscde_fvwmclnt 'Key Up A S -'`

In the same way, you can free up Meta+Space for layout changing (default is Alt+Space, so I avoided this one by default):

Key Space 4 A -

... you can bind Occupy Workspace than on some other combination if you wish.

Rofi (example: window, can be drun, ssh, etc ...)

`Key F12 A M f_Rofi window`

Graphical xrandr? Try arandr. It should be visible as "Screen Settings" on 7th subpanel when it is installed and NsCDE restarted.

**Comment by 31PNMR** [comment]
Greetings @NsCDE 

I'm sorry to reopen this, but I haven't had time to use NsCDE due to work.

I can confirm that on a completely fresh install of NsCDR on Arch, the `Shift+Arrrow` keybinding is present... somewhere. I'm coming from using Sway/i3, and I really wish there was a more central store and better organization of config files. I'm having such a hard time following FVWM and NsCDE config files. However, I was able to remove this keybinding.

With respect to `rofi`, I was able to convince (I think that's the best word) to show `drun` as default but it does not `show-icons`. Normally, in Sway/i3, I use the command `rofi -modi drun,run -show drun` to display the menu I want. I can't seem to find a config file that shows the exact command that is executed, or how to change the runtime options. What is the purpose of the `config` file in `$HOME/.config/rofi`? Changing the options there seems to have no effect.

With regard to display settings... The problem I'm having with multiple displays is that sometimes passing over the screen edge will cause the desktop to switch to another page. This particularly happens when connecting/disconnecting/reconnecting displays on a laptop, which is something I do several times a day. I guess I'm asking what is your suggestion for best dealing with this type of situation?

Thanks again for your hard work on this DE. It really is amazing.

**Comment by NsCDE** [comment]
Hi @31PNMR

1. Do not edit in /usr/share/NsCDE/fvwm ... everything what is in NsCDE system preferences for FVWM can be overrided and/or extended in ~/.NsCDE/<filename>.fvwmlocal. And for some keybindings, this is ~/.NsCDE/Keymenu.actions.

2. I have in my ~/.config/rofi this: "rofi.show-icons: true" ... and it works. If I temorary set it to false, icons are gone. So this is really a rofi question, not a NsCDE one. NsCDE while calling rofi only appends "-theme $HOME/.NsCDE/NsCDE.rasi".

3. In NsCDE 2.3, there will be a function which does:
    - Repositions all windows on all pages and workspaces according to saved resolution setting ~/.NsCDE/GeoDB.ini [1]
    - All windows that have width bigger then monitor resolution width will be resized to EWMH working area 96%
    - Same for height [2]


[1] GeoDB.ini is populated by Geometry Manager (Meta+Alt+G on focused window)
[2] This will be the rule for windows which does not have entry in GeoDB.ini

If you want to try it as feature preview, here it is below. Just append it to your ~/.NsCDE/Functions.fvwmlocal and restart NsCDE. Then you can manually call it like `nscde_fvwmclnt RepositionAllWindows`. It should be usefull with new FVWM3 1.0.5.

For screen edges, try to append in your ~/.NsCDE/NsCDE.conf `EdgeThickness 2` - see fvwm manual for this.

Here is the preview function. It needs some polishing still, as well as easy way to include escape for particular apps in it. Remember to remove this when upgrading to NsCDE 2.3, and careful with pasting this ...


```
# For 2.3 ... local test
DestroyFunc f_RepositionAllWindows
AddToFunc f_RepositionAllWindows
+ I PipeRead "echo 'All (CirculateHit, !FrontPanel, !NsCDE-Subpanel*, !Wmstickynotes, !Iconic, !Pidgin) InfoStoreAdd wids \"$[infostore.wids] $[w.id]\"'"
+ I f_ReconfWinSizePositionLoop $[infostore.wids]
+ I InfoStoreRemove wids

DestroyFunc f_ReconfWinSizePositionLoop
AddToFunc f_ReconfWinSizePositionLoop
+ I PipeRead "for wid in $[1-]; do ${NSCDE_TOOLSDIR}/usleep 250000 ; echo f_ReconfWinSizePosition $wid; done"

DestroyFunc f_ReconfWinSizePosition
AddToFunc f_ReconfWinSizePosition
+ I WindowId $0 (AcceptsFocus) Focus
+ I WindowId $0 f_StatefulRestoreMaximize 8 9 10 11 2 Maximize false
+ I WindowId $0 PipeRead "echo InfoStoreAdd wingeo \\\"$($[NSCDE_TOOLSDIR]/confget -c $[FVWM_USERDIR]/GeoDB.ini \
  -s $[infostore.lscrn.$[pointer.screen].width]x$[infostore.lscrn.$[pointer.screen].height] \
  -k $[w.resource],$[w.class] || echo 0)\\\""
+ I Test (!EnvMatch infostore.wingeo 0) WindowId $0 (!FixedSize,!FixedPosition) ResizeMove $[infostore.wingeo]
+ I Test (!EnvMatch infostore.wingeo 0) WindowId $0 (FixedSize) f_RepositionWindowMove $[infostore.wingeo]
+ I Test (!EnvMatch infostore.wingeo 0) WindowId $0 (FixedPosition) f_RepositionWindowResize $[infostore.wingeo]
+ I Test (EnvMatch infostore.wingeo 0) WindowId $0 (CirculateHit) PlaceAgain
+ I Test (EnvMatch infostore.wingeo 0) WindowId $0 (CirculateHit, !Iconic, !FixedSize, !FvwmPager, !stalonetray, !gkrellm) \
  PipeRead "if [ $[w.width] -gt $[vp.width] ]; then echo \"Resize 96wa keep\"; fi"
+ I Test (EnvMatch infostore.wingeo 0) WindowId $0 (CirculateHit, !Iconic, !FixedSize, !FvwmPager, !stalonetray, !gkrellm) \
  PipeRead "if [ $[w.height] -gt $[vp.height] ]; then echo \"Resize keep 96wa\"; fi"
+ I Test (EnvMatch infostore.lscrn.sls 1) MoveToScreen $[w.screen]
+ I InfoStoreRemove wingeo
```

**Comment by sjlongland** [comment]
I found the defaults were also interfering with applications, for instance in Firefox using shift-arrows to highlight text was broken.

```
# Disable NsCDE annoying defaults
Key Left A S -
Key Right A S -
Key Left A C -
Key Right A C -
```

That got things somewhat back to normal, although I note somewhere the highlight colour in Firefox presently looks identical to unselected text, so it's hard to know if text is actually highlighted and if so, where.  I guess I've got a colour setting that needs tweaking.

I'd be useful to be able to bring-your-own keybindings without having to "unset" the NsCDE standard ones.

**Comment by NsCDE** [comment]
Hi @sjlongland

This **is** the right way to nullify some key binding from default set. Just use it, and if you spot that some key binding of NsCDE clashes with some important app, do not hesitate to tell me that here. Obviously, sane key bindings are work in progress still ...

For Firefox, you can use full CSS integration as described in "Mozilla Integration" (rightmost subpanel with help), or you can use something like this in ~/.mozilla/firefox/<profiledir>/chrome/userContent.css:

```
::selection {
  background-color: black;
  color: white;
}
```
