### ISSUE TITLE
What are the best file manager, terminal, and other basic utilities for NsCDE?

### ISSUE THREAD

**Issue by daemonspudguy** [NsCDE/NsCDE#119]
Which ones fit the best?

**Comment by Pi-Time** [comment]
From my Debian-based NsCDE setup:
- File manager: nemo
- Terminal: xfce4-terminal (would use xterm, but couldn't permanently set the font size to something reasonable)
- Text editor: mousepad and Geany
- Calendar: Osmo
- Calculator: mate-calc (better than xcalc on 1080p displays)

- Volume control: pavucontrol
- Network management: nmtui alongside nm-connection-editor
- Bluetooth management: blueman-manager
- Display settings: arandr
- Printer manager: system-config-printer
- Scanner: simple-scan
- Keyring management: seahorse

- Login screen: wdm
- Task manager: htop and xfce4-taskmanager
- Input switcher: ibus
- mspaint equivalent (when I don't want to deal with GIMP): xpaint
- Battery tray indicator and low battery notification: cbatticon

For those with touchscreen laptops:
- On-screen keyboard: xvkbd
- Pen input: cellwriter
- Notes and PDF annotations: xournal

qt5ct and gtk3-nocsd will also get QT and those pesky new Gnome apps to fit the theme. If libreoffice is being slow, uninstalling libreoffice-gtk3 and applying the gray libreoffice theme will speed it up while still fitting with the NsCDE appearance.

**Comment by NsCDE** [comment]
Ok, FYI, author (me) is using:

- FileMgr: pcmanfm-qt
- Term: mate-terminal (with NsCDE config from ~/.NsCDE/libexec/colormgr.local)
- PDF: qtpdfview, xournal
- Mail: Thunderbird (with NsCDE CSS)
- Browser: Firefox (with NsCDE CSS)
- Task mgr: qps
- Local monitoring: gkrellm
- X editor: Gvim
- X Calc: kcalc (with NsCDE config from ~/.NsCDE/libexec/colormgr.local)
- Mixer: pavucontrol

... but tastes varies between people of course.
