### ISSUE TITLE
Debian Dependencies

### ISSUE THREAD

**Issue by msolisaguero** [NsCDE/NsCDE#120]
When installing in debian, you get dependency errors while running   ` ./configure` _"missing headers..."_
To solve these dependency errors, should run:
`sudo apt install -y libx11-dev libxext-dev gettext automake`

then one could continue with the installation instructions by: `./configure & make & make install`

**Comment by NsCDE** [comment]
Thanks. Updated INSTALL.md to notify this for all systems in master tree.
