### ISSUE TITLE
Fpclock 

### ISSUE THREAD

**Issue by josvanr** [NsCDE/NsCDE#123]
Hi Hegel3d,

I'm back again! :) I was looking at the front panel clock again after a long time, and have adapted the c code to make it resemble more the original cde clock, with the triangular hands etc. Now I was wondering why the clock in your panel version has cde colorset 3 I believe, while in the original it has the same color as the front panel background. I've been trying to figure out how the clock gets it's color, but i've finally given up, hence this message. I tried to grep Fpclock and fpclock etc but it simply eludes me. Maybe you can give me a hint :)

I'll then copy your project to my own github and upload the changes to the clock hands, if you  are interested...

thnx!

Jos

**Comment by josvanr** [comment]
Aha! 

/usr/local/share/NsCDE/config_templates/progbits/type_b5/Fpclock.xpm

now in the bg color of the front panel.. Man that took some digging :)

**Comment by josvanr** [comment]
I do need to ask: the xpms for the workspace buttons are also in these directories. So that means, if the user wants to change the color of the background, these xpms need to be moved. Will the xpm for Fpclock stay in there, or can the color be set elsewhere (which then would move the file to another 'type_b*' directory?

**Comment by NsCDE** [comment]
Hi @josvanr Nice to read you again! :-)

FrontPanel clock: NsCDE has bigger and a bit different clock. Default one from CDE is really messed up and barely readable. I think it is using top shadow color of CDE color 6 for some weird reason. This is probably only visual change by default which I made here. Pclock defaults together with bigger Fpclock.xpm are ok. You can find in the documentation a way to redefine this in ~/.NsCDE/FrontPanel.actions to look as a Solaris Earth clock.

If you have hacked pclock in the way that it has backward look possibility, I can include it as an option for those who want it like that. Just make me some nice diff so I can test it.

XPMs WSMXBackBtnX are used only to give extra one pixel to buttons top and bottom shadow, to have in-pixel look as CDE one. Otherwise, buttons of the Workspace Manager in the middle of FrontPanel are Button widgets of WSM, WSM-2, WSM-4, WSM-6 and WSM-8 FvwmScript apps. This xpms are processed and put in user's  ~/.NsCDE/icons/NsCDE/ by Color Style Manager.

**Comment by josvanr** [comment]
[clockfiles.tar.gz](https://github.com/NsCDE/NsCDE/files/9913023/clockfiles.tar.gz)

I put the 2 modified files for pclock in this zip file. It now also has a 'sweeping' second hand, hope you like that...


 


I tried your suggestion from the manual to put Solaris Earth on the clock but it doesn't seem to work. I copied Frontpanel.actions to my fvwm userdir 
but the file doesn't seem to get read. If I change things in that file, there is no 
effect, even when it is empty, the panel still appears in the same way.
The environment variable is set correctly I believe:

jos1@xuV:~/.NsCDE$ echo $FVWM_USERDIR
/home/jos1/.NsCDE

If I make changes to Frontpanel.actions in the /usr.../defaults directory, the changes
to take effect. BUT... I pasted the code snippet from the manual in there, that 
re-defines the first button:

 Btn1,__APPLET__,M1,"Swallow (Respawn) \\"pclock\\"
   \\"Exec exec $NSCDE_TOOLSDIR/$(uname -s)_$(uname -m)/fpclock
   -H red -S white --hands-width=4
   --hour-hand-length=15 --minute-hand-length=20
   --second-hand-length=22 -w 
   -B $NSCDE_DATADIR/icons/NsCDE/SDtEarth.l.xpm\\",Exec exec firefox

   Btn1,,M2,FVWM,Nop

   Btn1,,M3,FVWM,f_FrontPanelPropsMenu 1 Browser



But the clock still seems to appear in the same way, no change. also if i restart
nscde. The icon SDtEarth.l.xpm does seem to be present in the icons directory...



Does it still work in your setup? Maybe I'm doing something wrong, not sure...


Jos

**Comment by NsCDE** [comment]
Hi @josvanr

It is `FrontPanel.actions` not `Frontpanel.actions`. This is what is probably bothering you.

It works, but must be in one line (it didn't fit in docs). Copy and paste from HTML, various markups (like this one in github) can break things.

Thanks for the clock patches, I will take a look and test when I find time, busy week now ...

**Comment by NsCDE** [comment]
Leave this open for fpclock for now.

It looks nice, but sweeping second really looks like it is drunk. It irritates a bit. I think we can make it without that by default and convert this behaviour into an option. Hands should be a bit longer specially for minutes. I will take a look into this again ...

**Comment by josvanr** [comment]
:) Well I can always make a fork. You can turn it off again by checking for int seconds so... 
The length of the hands can also be easily modified..

**Comment by NsCDE** [comment]
Yes, I have found this for seconds, and maybe I can turn it to cmdline option. Other thing is hour and minute hands. They are calculated ok, but the final result is shortening and cutting topmost 2-3 pixels. Probably it has to be "artificially" added back to your hx1, hx2, hy1 and hy2 ... this kinda worked, but I'm not sure it is proper yet. Anyway, this is something that I will like to include in 2.3. Thanks.

**Comment by NsCDE** [comment]
Final version of @josvanr patch commited in master. IMO, this is optimal towards backward look and visibility on today's displays. Old wall clock style "sweeping" is funny, but not part of the original and somewhat attention distractor, left it out.
