### ISSUE TITLE
Where are the clock and caledar icons located?

### ISSUE THREAD

**Issue by Lixkote** [NsCDE/NsCDE#125]
Hello, thanks for help with previous things, i managed to get the effects i wanted:
![image](https://user-images.githubusercontent.com/95425619/199241157-571b9fdc-7048-4091-8c12-9b7f07756546.png)

But one last thing to do was to replace the clock and calendar applet's background xpm's... And no matter what i replace in usr/share/NsCDE/icons/NsCDE and other dir's still the clock and calendar remains the same... Can you tell where the "real icons" are located? I mean these:
![image](https://user-images.githubusercontent.com/95425619/199241897-30b6f31a-e320-4b51-8861-8afe2fc5a4fa.png)

**Comment by NsCDE** [comment]
Hi,

You are really persistent. :-) You can either replace them by icons, or redefine their look to suit you.

Clock is generated from /usr/share/NsCDE/config_templates/progbits/type_b3/Fpclock.xpm which becomes ~/.NsCDE/icons/NsCDE/Fpclock.xpm, Caledar is the FvwmScript app, find it in the same place as WSM, it is called MonthDayApplet. It uses /usr/share/NsCDE/icons/NsCDE/FpCM.l.pm.

**Comment by Lixkote** [comment]
Hello, i replaced the clock xpms in these locations with my new one, but the clock still looks the same :c

**Comment by NsCDE** [comment]
Hi @Lixkote

Do `ps -ef | grep fpclock` to find path to the generated version in ~/.NsCDE. It is generated from the `/usr/share/NsCDE/config_templates/progbits/type_b3/Fpclock.xpm` really.

Restart Front Panel, easiest way is to restart NsCDE.

**Comment by Lixkote** [comment]
Hi,
Thanks to your help, i was able to make eveything look like i want.
Really thanks 👍 
![image](https://user-images.githubusercontent.com/95425619/199700856-63bbc264-6899-4237-bac3-38b8a17fc512.png)


Also, how can i make the FrontPanel icons automatically use the current system icon theme like adwaita, papirus etc. ?
I have tried changing the fvwmconf file like that but it refuses to load the icon.
![image](https://user-images.githubusercontent.com/95425619/199701400-2ea8cce3-825c-496b-ae87-f5f6bf16bc23.png)

**Comment by Lixkote** [comment]
What can i type as an value(in "NsCDE") for it to automatically change to the currently applied gtk icon theme?

**Comment by Lixkote** [comment]
I want to make something like an window which would get all of the installed system icon themes(usr/share/icons) an give an option to change with a few clicks
