### ISSUE TITLE
Client side decorations

### ISSUE THREAD

**Issue by josvanr** [NsCDE/NsCDE#129]
hi NsCDE / Hegel3d !

I'm looking at the CDE/Motif gtk themes again and was thinking about what to do with the new (well new..) client side decorations. In the current gtk3 theme, dialog windows that have csd, just appear without border, with a GtkHeaderBar on top. I looked at the css, and it is difficult to mimick Motif style window decorations with this. Another option would be to install gtk3-nocsd. Then the window manager just draws a border around all dialog windows. The GtkHeaderBar can then be css-ed to look as a kind of toolbar, using the '_sel' colors from cde. I was wondering what your thoughts are on this.. (not sure where to ask you, so I thought I'd just post it here)

thnx!

**Comment by NsCDE** [comment]
Hi Jos

Sorry for the late answer, I broke my arm, so I'm less at the keyboard and type slowly.

I'm more in favour of the gtk3-nocsd solution which is highly recommended with NsCDE. And yes, you are right: this so called header bar (GtkHeaderBar) should be colored in color 5, not color 6 in 8-color mode in main window, to mimic some (primitive) toolbar.

I will add this to TODO list for 2.3. Thanks.

**Comment by josvanr** [comment]
Hi Hegel,

o oh.. I hope you are ok ! :) Yes I'm gonna do that in my own theme as well. Supposedly there is also a patch for gtk4 floating around somewhere, see if I can find that....

good luck!

Jos

**Comment by tim78245** [comment]
Another solution may be gtk3-classic:

https://github.com/lah7/gtk3-classic

**Comment by josvanr** [comment]
Thnx! Interestig project. They also seem to be very active...

**Comment by NsCDE** [comment]
Hi @josvanr

Next version will color this so called "header bar" in toolbar colors, not menu colors, as you mentioned in the first post of this issue. Together with nocsd hacks, windows of this poor applications may look almost normal.
