### ISSUE TITLE
can't start

### ISSUE THREAD

**Issue by dchmelik** [NsCDE/NsCDE#13]
I've used CDE; would like to try NsCDE (first as a second X session.)  What happens is below.
```
d@tty1.cosmos:~$ exec /opt/NsCDE/bin/nscde
xdpyinfo:  unable to open display "".
Warning: DPI "" is not recognized as X DPI specification. Setting DPI to 96
Warning: cannot read /home/d/.NsCDE/Xdefaults file
Warning: cannot find /home/d/.NsCDE/app-defaults directory
Notice: /home/d/.NsCDE/Xset.conf does not exist
[fvwm][main]: <<ERROR>> can't open display
```

**Comment by NsCDE** [comment]
This is not designed to start X session, but to be started from $HOME/.xsession or from X display manager like sddm, lightdm, gdm, xdm etc. As if you started fvwm directly: it will not start X server. Either use display manger, or $HOME/.xsession and "startx". This will start first login setup mini-wizard.

**Comment by dchmelik** [comment]
I don't use display managers.

I haven't used FVWM (though FVWM2 is installed.)

My operating system (Slackware, but I will also try NsCDE on FreeBSD) has a configuration script (/var/log/setup/setup.xwconfig) for choosing which X window manager (WM) or desktop environment (DE) to make default for 'startx.'  After installing NsCDE, option didn't appear (neither does CDE but I think Enlightenment and some others do, as they meet certain standards.)

I don't know about any of this; no idea how to start NsCDE.  Apparently a second X session is started like (for enlightenment, or replacing name with xfce, etc.) 'xinit /etc/X11/xinit/xinitrc.enlightenment -- /usr/bin/X :1'... similarly for CDE, 'startx /usr/dt/bin/Xsession -- /usr/bin/X :1' (as documented, and they also have xinitrc.cde... not for NsCDE)... when I looked in $HOME/.xsession (I know nothing about) it's for starting KDE, not NsCDE.  There doesn't seem to be a .xsession nor xinitrc for NsCDE...

**Comment by NsCDE** [comment]
Looks like, your Xorg setup is not very common or usual. I have tested my releases on Fedora, Arch, Ubuntu, Debian, FreeBSD and occasionally other in virtual machines without issues.

$HOME/.xsession or $HOME/.xinitrc are not for starting KDE, but any DE or window manager which is defined on the end of that script.

Simply "exec /opt/NsCDE/bin/nscde" at the end of that file, without prior "exec" lines, should work with "startx".

**Comment by dchmelik** [comment]
I had to in .xinitrc.
