### ISSUE TITLE
missing missing required header files

### ISSUE THREAD

**Issue by dieu-the-man** [NsCDE/NsCDE#131]
i don't know how or why but i keep getting the same error of "missing required header files" and shape.h says no next to it when running the `./configure`, i don't know if it is a NsCDE or a dependence not working correctly but i cant find any thing on this issue so here i am.  (sorry if it is difficult to understand its late at night) 
![headerfilemissing](https://user-images.githubusercontent.com/114900321/202833703-51ec524c-42fd-48bd-911f-3c75850c8b16.jpg)

**Comment by NsCDE** [comment]
Sorry for the late answer, I broke my arm and I'm not often at the keyboard. Recovering.

You are missing libXext-devel or libxext6-dev or similary named (distribution dependent) package.
