### ISSUE TITLE
Feature request: Add cli options for various tasks

### ISSUE THREAD

**Issue by tim78245** [NsCDE/NsCDE#132]
I'm thinking like nscde-manager --restart-fp --restart-fp-lite --restart-fp-clock --restart-wm --style-manager, etc.

Perhaps also such like nscde-style-manager --theme broica, etc.

Because when someone closes the front panel, it is not trivial to reopen it and get access to all the things it offers, one has to dig for the functions.

**Comment by NsCDE** [comment]
Hi @tim78245

Command `nscde_fvwmclnt` is the wrapper to the all NsCDE FVWM functions and more. By examining what menu options do and looking at /usr/share/NsCDE/fvwm/Functions.fvwmconf you can do pretty much everything with it.

Changing theme is done with "themegen" internal utility which is in the `/usr/lib/x86_64-linux-gnu/NsCDE` or `/usr/lib64/NsCDE` ...
