### ISSUE TITLE
Style manager: click on "Screen", but nothing happens

### ISSUE THREAD

**Issue by mbert** [NsCDE/NsCDE#133]
OS: Fedora 37, NsCDE version 2.1.2

**Comment by NsCDE** [comment]
dnf install xscreensaver

**Comment by mbert** [comment]
xscreensaver is installed. It had been before. So it must be something different. Ist there any log file where error messages can be inspected?

**Comment by mbert** [comment]
Got it. It's `/var/log/messages` on Fedora, just grep for `gdm-x-session`. The problem is the command line: `xscreensaver -prefs` is not supported by version 6.05 which is running on my Fedora box. Instead `xscreensaver-settings` should be used. This may be version-dependent, which is of course rather inconvenient. Maybe a wrapper script would do, like `xscreensaver -prefs 2>/dev/null || xscreensaver-settings`?
I am not terribly literate in Fvwm configuration (I used to be better in the 1990s when it was my primary WM, but I have always found it overcomplicated), but is there a way to override that configuration in `~/.NsCDE` for now?

**Comment by NsCDE** [comment]
Hi @mbert

Thanks for this. Obviously I need to take care of xscreensaver changes in v 2.3 and make it work seamesly for all versions. Leave this issue open please.

**Comment by NsCDE** [comment]
This is now handled in f_Xscreensaver.
