### ISSUE TITLE
Double-clicking minimises window icon on the desktop leads to unusable state

### ISSUE THREAD

**Issue by mbert** [NsCDE/NsCDE#134]
OS: Fedora 37, NsCDE version 2.1.2

How to reproduce: minimise any Window to the desktop. The icon appears on the left side by default. When hovering the icon with the mouse the mouse pointer is flipped, i.e. points from bottom left to top right. Double-click the icon. The window is restored, but the mouse pointer remains flipped and can no longer be used. Also keyboard shortcuts no longer work, e.g. trying to minimise the window again or opening a shell window using Alt-F12. A kill -HUP on fvwm does not have any effect. All that seems left to do is kill the X session.

**Comment by NsCDE** [comment]
Bug is due to some core Xrog library security fix.

NsCDE 2.2 implements temporary workarounds for this erroneous behaviour. Upgrade. You have ready made RPM's here on downloads. The fv35 should be installable on fc37, if not, download src rpm and rebuild on fc37.

**Comment by mbert** [comment]
> Hi @mbert
> 
> Bug is due to some core Xrog library security fix.
> 
> NsCDE 2.2 implements temporary workarounds for this erroneous behaviour. Upgrade. You have ready made RPM's here on downloads. The fv35 should be installable on fc37, if not, download src rpm and rebuild on fc37.

I have built an rpm from version 2.2.6, thank you for providing the .src.rpm!
Unfortunately it seems the workaround does not work, the problem still occurs.
