### ISSUE TITLE
Idea: Use another mixer besides PNMixer

### ISSUE THREAD

**Issue by daemonspudguy** [NsCDE/NsCDE#136]
On systems with PipeWire, PNMixer does not work very well when combined with pavucontrol. Alsamixer (and PNMixer) will say that volume is set to 4 but anything using PulseAudio will say it's 35, at least on my system. I think using a PulseAudio-native system tray mixer would be a good idea.

**Comment by NsCDE** [comment]
@daemonspudguy you are right. This applet should not be pushed and recommended automatically, at least not without examining underlaying audio subsystem used.

Goes on TODO list ...

**Comment by NsCDE** [comment]
Removed pnmixer force in default Init.fvwmconf.
