### ISSUE TITLE
keyboard shortcuts

### ISSUE THREAD

**Issue by frostbane** [NsCDE/NsCDE#139]
By default, `Shift`+`arrow` keys move the mouse, and `Ctrl`+`arrow` keys does something else.

Is there a way to disable (or maybe a workaround) this feature? `Shift`+`left/right` is pretty much the de facto when using spreadsheets (in this era.) And `shift`+`left/right` is also used to select text. `Ctrl`+`left/right` is also used to jump between words in a text box. I don't think these keyboard shortcuts will go away anytime soon.

**Comment by marcdw1289** [comment]
There's some related info regarding keybindings in issue #118 that might help.
