### ISSUE TITLE
Firefox with more than 2 tabs crashes to login screen upon minimizing

### ISSUE THREAD

**Issue by h3ll0-w00rld** [NsCDE/NsCDE#141]
Running firefox with 2+ tabs will crash firefox upon minimizing, no logs were found after crashing sadly. 
OS: Arch (EndreavourOS)
Not a lot of info could be gathered on why it happens outside of the fact it kills the entire WM to login screen.

**Comment by NsCDE** [comment]
Hi @h3ll0-w00rld

I don't have EndrevourOS, just Arch in one of development VMs. Firefox doesn't crash ... not in Fedora, Debian, Suse, Arch, FreeBSD, OpenBSD ... where I test NsCDE code.

Must be something else then. Have you tried this under vanilla fvwm session or some other window manager?

**Comment by h3ll0-w00rld** [comment]
> Hi @h3ll0-w00rld
> 
> I don't have EndrevourOS, just Arch in one of development VMs. Firefox doesn't crash ... not in Fedora, Debian, Suse, Arch, FreeBSD, OpenBSD ... where I test NsCDE code.
> 
> Must be something else then. Have you tried this under vanilla fvwm session or some other window manager?

Hi, I found out the issue, it wasn't firefox w/ multiple tabs, it's the fact that any full screened app just crashes to login screen, also, not yet on vanilla FVWM, I will try it out when I have access to the laptop running NsCDE, and report back if it is only on NsCDE. ^^

**Comment by tim78245** [comment]
#113 ?
