### ISSUE TITLE
using Backdrops and Themes outside NsCDE 

### ISSUE THREAD

**Issue by d0sensuppe** [NsCDE/NsCDE#142]
I really have to thank you for all your hard work, that we may enjoy 90s gloryness on our modern hardware. 
I have been using your DE for a while now, especially on a machine hooked up to a CRT, unfortunately though fwm isn't quite what I would use for daily usage. I prefer tiling window managers like bspwm.   
 
So I'm wondering if it would be possible to use the backdrops and the style manager outside your environment. 
Best regards.

**Comment by NsCDE** [comment]
Hi @d0sensuppe

You can use Icons dir in /usr/share/icons/NsCDE and apply them in GTK and Qt/KDE (qt5ct) configurations.
You can create coloured theme against some of the color schemes in /usr/share/NsCDE/palettes with
/usr/lib/x86_64-linux-gnu/NsCDE/themegen or /usr/libexec/NsCDE/themegen, and also you can use
/usr/lib/x86_64-linux-gnu/NsCDE/palette_colorgen or /usr/libexec/NsCDE/palette_colorgen to generate
coloured backdrops for usage in other environments.

Example: palette_colorgen -n 8 -p /usr/share/NsCDE/palettes/Broica.dp -i /usr/share/NsCDE/backdrops/Emblem.pm -P 2 -b > Emblem.pm Where "-P " can have arg 3, 5, 6 or 7 for various colors of the named palette if -n is 8, not 4.
