### ISSUE TITLE
Workspace Menu & 'Available Applications' pane in Subpanels Manager no longer lists applications...

### ISSUE THREAD

**Issue by HenchM4n1k** [NsCDE/NsCDE#154]
It seems NsCDE is no longer able to locate applications stored within '/usr/share/applications'.

Probably related:

Using my system normally, I noticed a few bugs seemed to suddenly appear within NsCDE. Just to test, I launched Subpanels Manager and noticed that the GUI text and various window objects had shrunken, as if they'd reverted to a default state. Other things seemed to hang, and I couldn't press any buttons within NsCDE (such as the EXIT button), so I rebooted my system via terminal. After rebooting, systemd prompted various errors - one regarding GTK (cannot open display), another being Realtek firmware failing to load.

After troubleshooting, it seemed the system was trying to pull various resources but couldn't as the root partition was completely full. The culprit was a logging error (specifically, 'syslog', 'user.log', and 'messages'). These log files cumulatively jumped from ~2.00GB to well over 300GB in a blink of an eye. After deleting the contents of these log files, I rebooted into the system perfectly fine. I then configured logrotate to begin compressing future log files. Everything seems to be as it was, save for this one issue.

I've tried countlessly to restart all relevant processes, etc. No matter what I do, the issue continues. Here's what Subpanels Manager now looks like for me:

![ScreenAreaShot WSP_One 20230605 044211](https://github.com/NsCDE/NsCDE/assets/54715324/eb84bf9b-1cf1-4318-9b4f-13b8d00dc32d)

Via documentation, it seems NsCDE uses 'fvwm-menu-desktop' or other FVWM scripts to locate '.desktop' files in order to populate the list, though I cannot figure out how to restore this in the case of some kind of disconnect.

Here's my current system info:

![ScreenAreaShot WSP_One 20230605 182106](https://github.com/NsCDE/NsCDE/assets/54715324/4b087ee7-eca5-4189-9aff-a008c068fc81)

One thing to note; I'm not sure what's using so much memory (up to 81%). I suppose that's another thing I'll have to figure out.

**Comment by NsCDE** [comment]
Hi

Have you tried to run fvwm-menu-desktop manually to see if there is any sensible output or error message?

What does "Watch Errors" from 7th submenu have to output when you run Install Icon? This is a content of the ~/.xsession-errors.

I guess probably some python package is missing which is required for fvwm-menu-desktop(1).

**Comment by HenchM4n1k** [comment]
>Have you tried to run fvwm-menu-desktop manually to see if there is any sensible output or error message?

Yep, I've run fvwm-menu-desktop numerously, but everything _seems_ to be as it should.

>What does "Watch Errors" from 7th submenu have to output when you run Install Icon? This is a content of the ~/.xsession-errors.

Interestingly, I cannot seem to locate the /.xsession-errors file now. I'm certain I've opened it in the past. I've tried 'whereis' and other means, but it now seems to be vapor.

>I guess probably some python package is missing which is required for fvwm-menu-desktop(1).

Yep, I thought so too. Sadly, I cannot seem to figure out which one is missing for the life of me. I certainly have not deleted or overwritten any archives where such a file might exist. Or, at least not manually. Possibly a software conflict?

**Comment by HenchM4n1k** [comment]
>Have you tried to run fvwm-menu-desktop manually to see if there is any sensible output or error message?

Yep, I've run fvwm-menu-desktop numerously, but everything _seems_ to be as it should. No error messages either.

>What does "Watch Errors" from 7th submenu have to output when you run Install Icon? This is a content of the ~/.xsession-errors.

Interestingly, I cannot seem to locate the /.xsession-errors file now (hidden or otherwise). I've now read that this way of logging was recently deprecated - instead using 'journalctl' for logs. Via this method, I can't seem to find anything relevant in any of the provided logs, but I will continue reviewing them.

>I guess probably some python package is missing which is required for fvwm-menu-desktop(1).

Yep, I thought so too. Sadly, I cannot seem to figure out which one is missing for the life of me. I certainly have not deleted or overwritten any archives where such a file might exist. Or, at least not manually. Possibly a software conflict?

**Comment by marcdw1289** [comment]
I just got hit by this today after updating software and NsCDE 2.3 on Void Linux.
Root menu has no entries, Panel Install Icon entries are empty as per the OP, and any Infostore panel entries launch nothing.

The Watch window shows no errors.
fvwm-menu-desktop at the terminal returns `cannot execute: required file not found`.
I have no clue what's missing or not found.

**Comment by marcdw1289** [comment]
@NsCDE 
I found out what the issue was, at least for me. The fvwm-menu-desktop script was missing the interpreter in the shebang line.
First line was `#!:`
Once that was fixed all was good with Install Icon and desktop menus.

**Comment by NsCDE** [comment]
Hi @marcdw1289

Report this to fvwm2/fvwm3 package maintainer of your OS/distro.

**Comment by HenchM4n1k** [comment]
@marcdw1289 

Unfortunately², the script seems to be written correctly on my end and can call fvwm-menu-desktop successfully via terminal. Currently using NsCDE 2.2.

I was thinking about switching distros anyhow, probably to Devuan. Might just install _only_ KDE (xfce and NsCDE do _not_ get along 😅) as an alternate DE, or maybe none at all aside from NsCDE 2.3 and dependencies.
