### ISSUE TITLE
i915 DRM hangs when running NsCDE

### ISSUE THREAD

**Issue by phoe** [NsCDE/NsCDE#157]
I am attempting to run NsCDE on a somewhat ancient Thinkpad R61i on debian sid. Upon opening the style manager and clicking around, NsCDE hangs and renders the window in an incomplete state until I click around. But then, clicking around causes it to do so twice more, with a crash always happening on the third time. This is always reproducible on my machine.

See the window on the bottom right:

![photo_2023-06-24_11-10-46](https://github.com/NsCDE/NsCDE/assets/15045546/f26ce850-32da-4cfe-8620-9626172bb6f1)

The kernel log shows the following:

```
[  172.095092] i915 0000:00:02.0: [drm] GPU HANG: ecode 4:1:9fe7fbfd, in Xorg [996]
[  172.387108] i915 0000:00:02.0: [drm] Resetting chip for stopped heartbeat on rcs0
[  172.489745] i915 0000:00:02.0: [drm] Xorg[996] context reset due to GPU hang
[  186.946894] i915 0000:00:02.0: [drm] GPU HANG: ecode 4:1:9fe7fbfd, in Xorg [996]
[  187.247018] i915 0000:00:02.0: [drm] Resetting chip for stopped heartbeat on rcs0
[  187.349679] i915 0000:00:02.0: [drm] Xorg[996] context reset due to GPU hang
[  194.110860] i915 0000:00:02.0: [drm] GPU HANG: ecode 4:1:9fe7fbfd, in Xorg [996]
[  194.405605] i915 0000:00:02.0: [drm] Resetting chip for stopped heartbeat on rcs0
[  194.507095] i915 0000:00:02.0: [drm] Xorg[996] context reset due to GPU hang
```

How do I begin debugging this?

**Comment by NsCDE** [comment]
Hi @phoe 

This is nothing really what NsCDE (or FVWM generally) can handle. My notebook is much newer, but display is also run by i915 and it works well. It is up to the kernel driver and Xorg driver ("intel"). Try to play with xorg.conf and "man intel" to see options. Check that you have newest firmware for i915. Google this dmesg errors above ... what can I tell you, good luck.

**Comment by phoe** [comment]
OK. So far, it seems that only NsCDE triggers this behavior, since LXDE and MATE both run fine on that machine; I wish I knew which exact behavior causes this i915 problem to manifest, since it's always reproducible on my machine.

I'll check the firmware and retry; thanks.

**Comment by NsCDE** [comment]
NsCDE and fvwm are pretty much modest in resource and exotic X features usage, but it looks like something is triggering this bug. Try with or without compton X compositor, this may make some difference for worse or better maybe.
