### ISSUE TITLE
Question: Hide dock and iconified window icons?

### ISSUE THREAD

**Issue by tim78245** [NsCDE/NsCDE#158]
So this probably sounds crazy but I'm looking to try out using all of NsCDE but with a 95ish panel instead of the presentation manager+dock way.

How can I add to my config file to not load the dock and iconified window icons?

**Comment by NsCDE** [comment]
Hi @tim78245 

Sorry for a delay, I was on my summer vacation.

For a Front Panel, you will have to edit /usr/share/NsCDE/fvwm/Main.fvwmconf (or /usr/local/share/NsCDE/fvwm/Main.fvwmconf, depending on your installation) and comment out

`+ I ModuleSynchronous FvwmButtons FrontPanel`

in StartFunction.

For icons ... Try to put `Style * NoIcon` at the bottom of ~/.NsCDE/Style.fvwmlocal
