### ISSUE TITLE
GTK theme colors not updating with NsCDE color scheme

### ISSUE THREAD

**Issue by TurboWafflz** [NsCDE/NsCDE#165]
On my system running Arch Linux and the NsCDE AUR package, the GTK theme colors do not change when I change the NsCDE color scheme, instead, it always uses the colors from the default Broica theme. I've tried disabling and re-enabling the GTK integration in the style manager but it seems to have no effect, even after restarting applications and NsCDE itself.

Screenshot, showing correctly themed windows on the left and incorrectly themed GTK windows on the right:
![RootWinShot 20230905 112028](https://github.com/NsCDE/NsCDE/assets/26664670/55273157-9bd4-4686-9dc8-e4b0777533fc)

**Comment by NsCDE** [comment]
Hi @TurboWafflz

Engine for colouring GTK theme is probably missing some Python module.

Try to run manually /usr/lib/x86_64-linux-gnu/NsCDE/themegen or /usr/lib/NsCDE/themegen or /usr/lib64/NsCDE/themegen or or /usr/libexec/NsCDE/themegen or some of that combinations prefixed with /usr/local (find the damn themegen tool).

Example:
`/usr/libexec/NsCDE/themegen /usr/share/NsCDE/palettes/Autumn.dp 8 gtk2 gtk3`

Output should look like this:

```
Generate for Gtk2: gtk2
Generate for Gtk3: gtk3
/home/pkumar/.themes/NsCDE/img2/resource.indexed.png
/home/pkumar/.themes/NsCDE/img2/colorset6
/home/pkumar/.themes/NsCDE/img2/colorset4
```

Without errors or python traces.

**Comment by TurboWafflz** [comment]
That fixed it, thanks! I guess those dependencies are just missing from the AUR package, but I'm assuming you don't maintain that so it's not an issue for this repo. Thanks again for your help though!
