### ISSUE TITLE
Need help with Debian bookworm install

### ISSUE THREAD

**Issue by alexander-potemkin** [NsCDE/NsCDE#167]
Thank you for the project! I'm eager to set it up for me.

Could you please, help me with Debian Bookworm install?

I'm trying both deb install and source code, but it doesn't seem to work - please, see my output below:

Trying `dpkg -i`
```
(Reading database ... 130828 files and directories currently installed.)
Preparing to unpack nscde_2.3-3_amd64.deb ...
Unpacking nscde (2.3-3) over (2.3-3) ...
dpkg: dependency problems prevent configuration of nscde:
 nscde depends on ksh93 | ksh; however:
  Package ksh93 is not installed.
  Package ksh is not installed.
 nscde depends on stalonetray; however:
  Package stalonetray is not installed.
 nscde depends on xsettingsd; however:
  Package xsettingsd is not installed.
 nscde depends on imagemagick; however:
  Package imagemagick is not installed.
 nscde depends on python3-yaml; however:
  Package python3-yaml is not installed.
 nscde depends on python3-psutil; however:
  Package python3-psutil is not installed.
 nscde depends on python3-pyqt5; however:
  Package python3-pyqt5 is not installed.
 nscde depends on xdotool; however:
  Package xdotool is not installed.
 nscde depends on gettext; however:
  Package gettext is not installed.
 nscde depends on groff; however:
  Package groff is not installed.

dpkg: error processing package nscde (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for mailcap (3.70+nmu1) ...
Errors were encountered while processing:
 nscde
```

Trying `apt install` for from Install.md:
```

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
Package stalonetray is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package xutils is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  x11-xfs-utils x11-xserver-utils

E: Release 'x11-utils' for 'xutils' was not found
E: Package 'stalonetray' has no installation candidate
```

Any help would be much appreciated. Please, also let me know if any additional information could be of help!

**Comment by tim78245** [comment]
> Package stalonetray is not available, but is referred to by another package.

stalonetray had an issue building for bookworm and it wasn't fixed in time:
https://tracker.debian.org/news/1292554/stalonetray-removed-from-testing/

It will be back in the next version.

In the meantime maybe we want to move to wmsystemtray? Seems all the common linuxes has it, but not netbsd or openbsd.
wmsystemtray --small --non-wmaker --bgcolor rgb:ff/ff/ff --fgcolor rgb:00/00/00

> Package xutils is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> However the following packages replace it:
>   x11-xfs-utils x11-xserver-utils

> E: Release 'x11-utils' for 'xutils' was not found

I'm not replicating this error. I can `sudo apt install xutils` just fine. The metapackage is there:
https://packages.debian.org/bookworm/xutils

**Comment by Minda1975** [comment]
> Could you please, help me with Debian Bookworm install?
> 
Hello. Just build .deb package for your system.
Clone the repo, go to `/pkg/debian/`, open `control` file with your text editor, and move `stalonetray` from `Depends` section, to `Suggests` section.

Dependencies for making .deb package is:

`libc6-dev, libxext-dev, x11proto-dev, libx11-dev, libxpm-dev, ksh93u+m,  autotools-dev, automake, build-essential, devscripts`

Install these packages with command:

`sudo apt install libc6-dev libxext-dev x11proto-dev libx11-dev libxpm-dev ksh93u+m  autotools-dev automake build-essential devscripts`

Also, install runtime dependencies:

```
sudo apt install libc6 fvwm3 xsettingsd imagemagick x11-xserver-utils x11-utils cpp xterm python3 python3-xdg
 python3-yaml python3-psutil python3-pyqt5 xdotool xdg-utils gettext fonts-dejavu-core groff-base groff xclip xscreensaver dex gtk2-engines-pixbuf dunst qt5-gtk2-platformtheme qt5-gtk-platformtheme
```

And build the package, as described [here](https://github.com/NsCDE/NsCDE/tree/master/pkg )

**Comment by alexander-potemkin** [comment]
@tim78245 , @Minda1975 , thank you very much for your prompt and detailed responces!

As this NSCDE is my way to experiment on a new distribution (and I didn't have much of experience with Debian), I decided to try my ways with Manjaro/Arch instead - it seems like the installation there will be quite straightforward and it's an approach of Linux distribution that I didn't try.

Hope that this would be of help to anyone, who decide to give NSCDE a try on BookWorm.

**Comment by NsCDE** [comment]
@alexander-potemkin 

Package maintainer told me stalonetray will be in bookworm-backports. However, it isn't as I can check right now. Simply take the deb package from bullseye and install it. That's what I did after upgrade to Bookworm.
