### ISSUE TITLE
Picom config template missing in Debian package

### ISSUE THREAD

**Issue by docelic** [NsCDE/NsCDE#169]
When trying to run NsCDE, it asks:

```
Do you want to enable Picom X Compositor? y
Enabling: nscde_use_picom --> 1
cp: cannot stat '/usr/share/NsCDE/config_templates/Picom.conf: No such file or directory
Installing default Xset.conf example.
...
```

Looking into the `nscde` package files, there isn't any file named picom included.

Thanks!

**Comment by marcdw1289** [comment]
Same on Slackware (essentially a tarball install via SlackBuild script). Picom.conf does not get installed. The file is in the tarball though.
A quick look through Makefile.[am|in] indeed shows Picom.conf is not included in the install-data-hook.

**Comment by NsCDE** [comment]
Uff a miss. Bug.
Thanks @docelic and @marcdw1289 for spotting this.
Commited.
