### ISSUE TITLE
Pressed ctrl + c on bootstrap wizard how can I have it back?

### ISSUE THREAD

**Issue by agoodfellow123** [NsCDE/NsCDE#171]
Hello I accidentally pressed ctrl+c during bootstrap wizard process and I can't do it back.
I tried running /usr/local/libexec/NsCDE/bootstrap as well, doesn't do anything.
What should I do?

**Comment by Minda1975** [comment]
Hello.

Try to remove ~/.Nscde dir.

**Comment by agoodfellow123** [comment]
Thank you, that did it!
