### ISSUE TITLE
Switching workspace keeps showing global pager

### ISSUE THREAD

**Issue by renemadsen** [NsCDE/NsCDE#175]
When switching application or switching workspace, the global pager keeps showing up and taking focus.

![image](https://github.com/NsCDE/NsCDE/assets/76994/6bff3492-668c-4957-97e5-4b7b7dd942fb)

Worspace/page setup is like this:
![image](https://github.com/NsCDE/NsCDE/assets/76994/a0f48d33-aa12-4c47-9776-5d808975d430)

Can it be prevented, so it's "just" doing like fvwm and "just" switch workspace?

**Comment by NsCDE** [comment]
Hi @renemadsen

Put
`InfoStoreAdd nopage.workspace.pager 0`
in your ~/.NsCDE/NsCDE.conf

Then, restart NsCDE, or simply execute
`nscde_fvwmclnt InfoStoreAdd nopage.workspace.pager 0`
in terminal/shell to remove workspace popup pager in no-page mode.

**Comment by renemadsen** [comment]
@NsCDE it works as expected. So closing the issue.
