### ISSUE TITLE
Minimizing / Iconifying windows that overlap at least 2 other icons crashes NsCDE?

### ISSUE THREAD

**Issue by Legendary-Candice-Joe** [NsCDE/NsCDE#176]
I've been tinkering around with NsCDE and the original CDE, but one issue is for some reason NsCDE kept crashing.

At first I thought this was related to issue #113 but the fixes (or work-arounds) seemed to already be in place. It also doesn't freeze it just closes to my display manager.

The application doesn't matter, the icons themselves don't matter. But if I iconify a window that overlaps at least 2 other icons, it will crash. For a brief moment I can see the icons on the desktop, and usually the second one won't have it's picture rendered (I have no idea if that's helpful), and if I right-click the title bar of a window so it shows the icons on the desktop, then it won't crash.

Seems to be if any window overlaps any 2 icons and gets iconified, it just closes.
If it get's fixed then I can probably fully ditch the original CDE (which I know I certainly should).

My resolution is **1366 x 768** I have no idea if that helps.

I'm very sorry if this issue has been documented somewhere but I couldn't find it.

**Comment by timruff** [comment]
I'm the same issue, the issue has been solve with to install FVWM3.

**Comment by antonistsolomitis** [comment]
I confirm that upgrading fvwm to fvwm3 solves the crashing issue. There is a remaining bug: the part that the third applications window overlaps the icons of the first two, does not get redraw after the minimization of  the third app.
Steps to reproduce:
1. Open 3 terminals
2.  Minimize the two of them
3. Move the third terminal to overlap half of both icons of the minimized two terminals
4. Minimize the 3rd terminal
5. The icons of the first two do not get refreshed and the previously overlapped part remains grayish
6. It should redraw the minimized icons

**Comment by Legendary-Candice-Joe** [comment]
It seems that FVWM and FVWM3 are separate packages. I will try again later today.

**Comment by Legendary-Candice-Joe** [comment]
It seems that the issue is fixed with FVWM3. I noticed that the icons are still broken as mentioned above.

Thanks for the help!
