### ISSUE TITLE
Documentation missing to replace clock icon

### ISSUE THREAD

**Issue by drscream** [NsCDE/NsCDE#20]
It is mentioned in the documentation that it is possible to replace the pclock icon with the Solaris version (globe and hands). But somehow (from my point of view) the documentation should also describe how to replace it.

I tried to understand how it should work but somehow failed - that's also the reason why I open this ticket :-)

**Comment by NsCDE** [comment]
FrontPanel.actions on page 27 of the NsCDE.pdf should explain how to add custom applets by editing $FVWM_USERDIR/FrontPanel.actions. This should work for you, assuming you are on x86_64 Linux.

Btn1,__APPLET__,M1,"Swallow (Respawn) \\"pclock\\" \\"Exec exec $NSCDE_ROOT/bin/fpclock-Linux_x86_64 -H red -S white --hands-width=4 --hour-hand-length=15 --minute-hand-length=20 --second-hand-length=22 -w -B /export/home/mzubcic/useful/old_fvwm_setup_22_01_2019/dot_fvwm/Icons/DtIcons/DtEarth.l.xpm\\",Exec exec firefox

... of course, replace "Exec exec firefox" with with whatever you want, and restart Front Panel, or complete FVWM.

I have found someware my old DtEarth.l.xpm in 48x48 format suitable for pclock background. Here it is. Maybe I should include it in icon dir in the next release, together with this FrontPanel.actions line above as example in the docs. Ungzip before usage, github does not like XPM ...
[DtEarth.l.xpm.gz](https://github.com/NsCDE/NsCDE/files/4880873/DtEarth.l.xpm.gz)

**Comment by drscream** [comment]
Thanks a lot for providing more details. What I've found out so far about fpclock:

```
ERR: pixmap must be 64x64
```

So I think including `SDtEarth.l.xml` wouldn't help that much, as long as it's not provided in 64x64 pixel.

**Comment by NsCDE** [comment]
Wrong XPM. Try again. I have replaced attachment.

**Comment by drscream** [comment]
Thanks a lot. It works perfectly. Only for the record my current entry:

```
Btn1,__APPLET__,M1,"Swallow (Respawn) \\"pclock\\" \\"Exec exec $NSCDE_ROOT/bin/fpclock -H red -S white --hands-width=4 --hour-hand-length=15 --minute-hand-length=20 --second-hand-length=22 -w -B $FVWM_USERDIR/icons/NsCDE/SDtEarth.l.xpm\\",Exec exec firefox-bin
```

I will close this issue. Thanks again :-)
