### ISSUE TITLE
Panel not working properly on Ubuntu 

### ISSUE THREAD

**Issue by m217785** [NsCDE/NsCDE#24]
Greetings,
I have run the scripts on Ubuntu, but for some reason the Workspace selector on the panel is blank.
I've looked at some of the configurations, but have been unable to resolve.
Is there specific script to run or log to look at?

Thanks.

**Comment by NsCDE** [comment]
This is the double of the #17 issue which isn't yet resolved fully. Please see discussion on that issue and try what @pavroo has done: .xsession-errors for errors first. Last time I tested on Ubuntu, it was working fina as on Fedora and Debian. Closing this one as duplicate, continue under #17
