### ISSUE TITLE
Black fields when choosing GTK integration in Style Manager

### ISSUE THREAD

**Issue by mjohanning99** [NsCDE/NsCDE#25]
Hello,

so I've only just found out about this project and thought it was pretty cool; something, however, has been somewhat annoying, and that is the fact that whenever I choose the options of using the GTK integration options in the Style Manager, certain applications receive black fields where there really shouldn't be any. This is especially noticable on Firefox or Thunderbird as you can see on the screenshot below.

![2020-07-26-101836_1024x768_scrot](https://user-images.githubusercontent.com/3389797/88475003-546a8880-cf2c-11ea-91cc-c46215bcbda7.png)

This does not occur when I uncheck the GTK integration boxes – but then obviously I will also not have the theme on any GTK application, which is a tad annoying. I have tried changing some colours to white in the CSS files found in the `.themes/gtk-xx` directories and changing the `gtk-application-prefer-dark-theme` variable in the GTK-3 `settings.ini` file from `1` to `0`, but that didn't change anything either. 

Does anyone have this issue as well and perhaps some tips to mitigate this?

**Comment by mjohanning99** [comment]
Hey there,

thank you very much for your response. I have already had a feeling of this being an issue with GTK3 and especially Mozilla's products — I've had some theming issues with their programs before —, but it's still unfortunate that it does this. I will attempt to follow your advice of adding the `chrome` sub-directory and the corresponding `.css` files to it.

**Comment by NsCDE** [comment]
There is no obvious solution for some GTK3 apps currently. Closing this for now.
