### ISSUE TITLE
Disable switching virtual pages with mouse?

### ISSUE THREAD

**Issue by mjohanning99** [NsCDE/NsCDE#30]
Hey there,

I was wondering whether there was any way of disabling the switching between different pages of a Workspace via the mouse. It, unfortunately, frequently happens that I accidently switch to a different page by having my mouse be too close to the edge of the screen. I was unfortunately unable to find any information regarding this in the documentation.

**Comment by NsCDE** [comment]
Yes.
Open Style Manager, Window Style Manager, choose configuration section Page Edges, and then choose "Disable Page Change On Screen Edge" and press OK for reloading things.

This is described in the chapter 4.17.3 of the manual.

**Comment by mjohanning99** [comment]
Hey,

the problem appears to have been my screen being too large for the settings window and my thus being unable to find the "Page Edges" section. The screenshot below is how the settings opened, and I only by opening it on page three and then scrolling upward was I actually able to see the different settings.

Thank you for your help, though!
![RootWinShot 20200830 153245](https://user-images.githubusercontent.com/3389797/91660491-96ac5a00-ead6-11ea-873f-e96a0e690015.png)

**Comment by NsCDE** [comment]
Interesting. I think I will have to fix or leave to FVWM Style Managers initial window placement. BTW, you don't have to go to upper page to catch it, right click-and-hold on the borders of the window will start to move it, as well as Alt+F5 or Meta+F7 (center window).

What resolution is this? 1600x900 or similar seems to me.

**Comment by NsCDE** [comment]
Got it, it is vertically 768p. Initial geometry was wrongly pasted from some higher resolution. I will fix this in initial GeoDB.ini.
