### ISSUE TITLE
fonts are sort of screwed up after installing this

### ISSUE THREAD

**Issue by brightersun99** [NsCDE/NsCDE#33]
I installed this on arch, later quit using it due to instablity, but it seems to have messed with my fonts now. They look off, as if I were on the wrong resolution or they were stretched. Any ideas on how to reverse this?

**Comment by brightersun99** [comment]
its also really screwed with my mimeapp defaults i can no longer set anything as a default

**Comment by NsCDE** [comment]
1. Just run preferences of whatever desktop you are now using, or qt5ct for Qt based apps and set font you want. You can also edit $HOME/.gtkrc-2.0 and $HOME/.config/gtk-3.0/settings.ini and set new XFT font definition manually.

2. NsCDE does not mess with MIME preferences, but I'm not sure I understand second question/statement.
