### ISSUE TITLE
NOAPP in context of a web browser

### ISSUE THREAD

**Issue by 97-109-107** [NsCDE/NsCDE#34]
First of all, thank you for the great effort clearly put into this project!

I'm getting a NOAPP message when I try to launch anything related to the web browser from the main panel (documentation or right click on the clock icon)

My enviroment has a default web browser - other application can call the browser, my `$BROWSER` is also set.

----

I saw that `NsCDE/share/fallback/app-catalog/www-browser` has a list of binary names, my particular browser is not on the list.
I've edited the file to include it, restarted the enviroment but didn't see a change

**Comment by NsCDE** [comment]
Hi

You forgot to tell me the name of the browser. If you tell me the name of your browser, I can include it on the list for the next release. Thanks.

**Comment by 97-109-107** [comment]
Hi, they are

- qutebrowser
- firefox-developer-edition

Thank you

**Comment by NsCDE** [comment]
You are fast. In the meantime I edited my text. Please read and try this diagnostic. Thanks.

**Comment by 97-109-107** [comment]
Thank you for the prompt reply; see the two outputs below. `xsession-errors` was empty
I didn't logout, I used the command _restart nscde_ in the desktop context menu.

```
ksh -x /opt/NsCDE/libexec/appfinder qutebrowser                                                                                                                          
+ [ xqutebrowser '==' x ]
+ CatName=qutebrowser
+ [ ! -r /opt/NsCDE/share/fallback/app-catalog/qutebrowser ]
+ echo NOCATALOG
NOCATALOG
+ exit 2
```

```
ksh -x /opt/NsCDE/libexec/appfinder firefox-developer-edition                                                                                                          
+ [ xfirefox-developer-edition '==' x ]
+ CatName=firefox-developer-edition
+ [ ! -r /opt/NsCDE/share/fallback/app-catalog/firefox-developer-edition ]
+ echo NOCATALOG
NOCATALOG
+ exit 2
```

**Comment by NsCDE** [comment]
Sorry, I was in hurry before work. I gave you the wrong instructions. Please do this:

ksh -x /opt/NsCDE/libexec/appfinder www-browser

... where "www-browser" is literal string, not place holder.

Thanks.

**Comment by 97-109-107** [comment]
No problem, it's
```
+ [ xwww-browser '==' x ]
+ CatName=www-browser
+ [ ! -r /opt/NsCDE/share/fallback/app-catalog/www-browser ]
+ found=0
+ read appname
+ cat /opt/NsCDE/share/fallback/app-catalog/www-browser
+ whence -q firefox
+ read appname
+ whence -q qutebrowser
+ echo qutebrowser
qutebrowser
+ found=1
+ break
+ ((1 == 0))
```

**Comment by NsCDE** [comment]
It is found as you can see. I installed qutebrowser in the VM and tested. It works if it is defined in the www-browser file at the beggining before other browsers on the system.
To define it as default in NsCDE, put
`InfoStoreAdd browser firefox`
into your $HOME/.NsCDE/NsCDE.conf and use Workspace Menu right click on the root window, choose "Restart NsCDE" and restart.

**Comment by 97-109-107** [comment]
Adding 
```
InfoStoreAdd browser qutebrowser
``` 
has fixed the issue
