### ISSUE TITLE
(request) icon theme

### ISSUE THREAD

**Issue by onestep749** [NsCDE/NsCDE#36]
Hi, I realyl like the icon theme and tweaks to QT and GTK that this DE applies while in use. 

I was wondering how I could have those things without using nscde, it is kind of unstable at the moment. 

i tried just copying the icons to another pc but they do not seem to be useable that way.

**Comment by NsCDE** [comment]
For theme, generator is /opt/NsCDE/libexec/themegen.py and all components it uses from /opt/NsCDE/lib/python. Together with palette files in /opt/NsCDE/share/palettes which are basic fuel for generating CDE/NsCDE color theme, this generates $HOME/.themes/NsCDE which if copied to any other user or system in the same place and choosen in $HOME/.gtkrc-2.0 and $HOME/.config/gtk-3.0/settings.ini or with XSETTINGS daemon must work.

Icon theme is another thing. Directory /opt/NsCDE/share/icons/freedesktop/theme/NsCDE can be placed in system without NsCDE in /usr/share/icons or /usr/local/share/icons and choosen in settings, gtkrc etc ... for Qt to work, QT "gtk2" engine (bridge) must be choosen and used.

**Comment by onestep749** [comment]
Thanks!! these are really great tools, I use them with regular CDE and
its great.
