### ISSUE TITLE
NsCDE with Gnome-Session doesn't work on SparkyLinux (debian)

### ISSUE THREAD

**Issue by daemonspudguy** [NsCDE/NsCDE#37]
I get an error saying "Uh-oh. Something's gone wrong"

**Comment by NsCDE** [comment]
Hi,

This text is not part of any NsCDE error message. Since there is no description of the setup or any logs, it is impossible to progress with this problem. Please collect X session logs data, Display Manager logs, detailed description of what happened and so on, this is not enough.

**Comment by daemonspudguy** [comment]
Nevermind, the latest version of NsCDE fixed the desktop file. I just needed to copy it to /usr/share/xsessions.
