### ISSUE TITLE
Color Theme Extensions

### ISSUE THREAD

**Issue by oliversandli** [NsCDE/NsCDE#38]
Firstly, I love NsCDE!! It's fast, clean, and beautiful!

Is there a way to write an extension to apply NsCDE's color themes to other programs? I use the [kitty terminal](https://sw.kovidgoyal.net/kitty/), and it would be awesome to integrate it with NsCDE's colors. Thanks for any help!

**Comment by NsCDE** [comment]
Hi @oliversandli

Yes it has. In ~/.NsCDE/libexec there is colormgr.local and fontmgr.local can be added. In default colormgr.local you will find examples for mate-terminal and gkrellm. This can then be run with palette and number of colors path manually, or by confirming existing (or choosing new) color scheme in Color Style Manager. 

See /opt/NsCDE/share/doc/examples/README.colormgr.local and section 15.3 of NsCDE manual.

**Comment by oliversandli** [comment]
After analyzing `colormgr.local`, I found that `$PPATH` points to a `*.dp` file. What do the 12-digit hex numbers mean in those files? For instance, in `Broica.dp`:
```
#ed00a8007000
#9900991b99fe
#89559808aa00
#68006f008200
#c600b2d2a87e
#49009200a700
#b70087008d00
#938eab73bf00
```
I assume these correspond to the 8 colors shown in the Color window of the Style Manager? If so, how can I use them as regular 6-digit colors?

**Comment by NsCDE** [comment]
This are the CDE color palette files. This kind of color representation was characteristic then, and it is used in NsCDE today so old palettes are compatible out of the box. This can be converted into familiar 6-digit hex by simply discarding every second pair of numbers (3,4 7,8, 11,12).

If your terminal app does not recognise 12-digit hex (many do), you can automatically convert them by specifiying "-s" to /opt/NsCDE/libexec/nscde_palette_colorgen.py after -p $PPATH and -n $NCOLORS.

**Comment by oliversandli** [comment]
Thanks for the clarification! Preliminary testing seems very promising.
