### ISSUE TITLE
Wallpaper file picker can't enter folder with spaces in name

### ISSUE THREAD

**Issue by 97-109-107** [NsCDE/NsCDE#39]
First of all thank you for the 1.1 release. The added tile support is very exciting!

I wanted to report that the new dialog window for picking a background picture seems to be unable to traverse into directories with spaces in the name. Attached a screenshot of a the dialog box. At the pictured level, it can traverse deeper into folders without a space in the name.

![ScreenShot 'FvwmScript' 0x6600001 20201222 120321](https://user-images.githubusercontent.com/1902438/102882565-d4027200-444e-11eb-9b0c-e51698e1616f.png)

**Comment by NsCDE** [comment]
Try now from master tree. It should work for spaces. It is not perfect, but will do for now.

**Comment by 97-109-107** [comment]
Solved now
