### ISSUE TITLE
Running wine

### ISSUE THREAD

**Issue by danger89** [NsCDE/NsCDE#43]
Unable to run [wine](https://www.winehq.org/) in NsCDE:

```sh
$ wine

ERROR: ld.so: object '/opt/NsCDE/lib/XOverrideFontCursor.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
```

It's a 64-bit so file, that always gets preloaded somehow, but Wine is often still used (for good reasons) as a 32-bit binary.

Please, fix!

Regards,
Melroy

**Comment by NsCDE** [comment]
Hi,

Thanks for this report. This is just a warning right? If not, do `unset LD_PRELOAD` in the terminal before starting wine.
I must think how to handle this in a mixed 32/64 Linux environment. Unfortunately Linux dynamic linker doesn't have LD_PRELOAD_32 and LD_PRELOAD_64 built in. :-(

FYI, in FVWM3, there is no need for this LD_PRELOAD hack anymore.

Leaving this open for now.

**Comment by danger89** [comment]
Try using a second $LIB variable to switch between 32 & 64 bit:
```
LD_PRELOAD='/$LIB/lib_init.so' 
```

**Comment by NsCDE** [comment]
Thanks for pointing this out. I omitted that in ld.so(8). This goes to TODO list for 1.2.

**Comment by NsCDE** [comment]
Hi,

With all Unix and Linux variants and their different ways of handling LD_PRELOAD for 32/64 bits, I have found even better way to do this, and that is to preload the lib only for FvwmScript. That way, only one lib hack needs to be installed and environment is not polluted with unnecessary LD_PRELOAD anymore. Fixes are in in current master tree.

**Comment by danger89** [comment]
That is just great news, thanks!!
