### ISSUE TITLE
Keybinding Context missing explanation

### ISSUE THREAD

**Issue by danger89** [NsCDE/NsCDE#44]
Hi,

The following is explained in the header of `/opt/NsCDE/config/NsCDE-Keybindings.conf`:

```
# Contexts:
#     R = Root Window                 rrrrrrrrrrrrrrrrrrrrrr
#     W = Application Window          rIrrrr<---------^rrrrr
#     F = Frame Corners               rrrrrr[13TTTT642]rrrrr
#     S = Frame Sides                 rIrrrr[wwwwwwwww]rrrrr
#     T = Title Bar                   rrrrrr[wwwwwwwww]rrrrr
#     I = Icon                        rIrrrrv_________>rrrrr
#                                     rrrrrrrrrrrrrrrrrrrrrr
```

But I'm missing the context letter 'A' meaning in the list of explanations. Most likely 'A' in context also mean 'ANY'? Example:

`Silent Key Left A S CursorMove -1 0`

- Silent -> supress errors
- Key Left -> Left key
- A -> _**?**_
- S -> Shift
- CursorMove -1 0 -> the command

Ps. Also the ASCII art on the right side, is a vague for me.

Regards,
Melroy

**Comment by NsCDE** [comment]
This comment was old remain of original FVWM default config. I left it there for one-letter options reminder. A means Any contect. See fvwm(1) man page, look at Key and Mouse definitions, options and arguments.
