### ISSUE TITLE
.dtwmrc parser

### ISSUE THREAD

**Issue by brightersun99** [NsCDE/NsCDE#45]
You are quite talented and creative with python. Could we get a dtwmrc parser for porting our settings over?

**Comment by ThomasAdam** [comment]
Hi @brightersun99 

Can you provide an example of `.dtwmrc` please?

**Comment by NsCDE** [comment]
Hi
It was last century when I really customized this by editor on some Sun stations. I see now that syntax is cleanly readable. My assumption is you put here custom key bindings, functions, menus etc.

I'm currently in the dormant state with development, and slowly coming back, so do not expect this over the night.

As @ThomasAdam pointed out, please provide your example. Together with online resources, there should be enough material for this "config migration" script.

**Comment by NsCDE** [comment]
There is no response since february. I will close this one.
