### ISSUE TITLE
NsCDE 1.1 Feedback

### ISSUE THREAD

**Issue by leoctrl** [NsCDE/NsCDE#47]
Hi there,
I recently discovered NsCDE thanks to a link in the Wikipedia article about the original CDE; I've been using it regularly for about a month and appreciate its consistency and extensive documentation, which are indeed not so common.
So it's with an absolutely positive approach that I'd like to report a few, really small things that I've noticed here and there; I see them not as "issues", just little suggestions, but I don't know where else to report them so I'm posting them here.
Thanks for your attention.

In no particular order:

1. $HOME/.config/gtk-3.0/settings.ini
When I switched back to Xfce after setting up NsCDE, I noticed that everything had gone dark, even though I never chose any Gtk dark theme for Xfce; after much head scratching, I noticed this directive
gtk-application-prefer-dark-theme = 1
in file $HOME/.config/gtk-3.0/settings.ini.
I was quite sure I hadn't set that myself; to verify that I created a new test user, checked that no such settings.ini file existed for that user, started NsCDE, and after that I did find that file with that directive in it.
I switched back to my regular user and changed that directive's value from "1" to "0": Xfce adopted my favorite light theme again, while I didn't notice any changes in NsCDE.
To avoid confusion, if that directive is not necessary for NsCDE I'd suggest to remove it, and if it is instead to document it in the FAQ and/or Manual.

2. $HOME/.themes/NsCDE/gtk-3.20/widgets.css
When clicking a toolbar button of a Gtk application I noticed an horizontal flickering of the toolbar: the farther on the right the button, the wider the flickering (e.g. the 'Exit' button of the Geany text editor)
Eventually I found out that commenting out the 'padding' property (line 298) of selector
'button:active, button:checked'
in file $HOME/.themes/NsCDE/gtk-3.20/widgets.css stopped that annoying flickering.
(I am not a Gtk themer and my knowledge of CSS is really basic, there may other/better ways of achieving this)

3. /opt/NsCDE/libexec/nscde-acpi
The Linux distribution I'm currently using is MX, which is based upon Debian stable, has systemd installed for compatibility, but doesn't use it as its init system; as a result of this, /opt/NsCDE/libexec/nscde-acpi returned (in)famous error
"System has not been booted with systemd as init system (PID 1). Can't operate"
when trying to shut down the system.
One solution I found on the Internet is to check the output of command
ps -p 1 -o comm=
which in my case returns "init", to determine whether systemd is actually being used as init system or not.

4. NsCDE-Keybindings.conf Manual chapter
I wanted to remove some of NsCDE's default key bindings, but since I'm completely unfamiliar with Fvwm I didn't know how to do that; after unsuccessful search on the Internet I did find the very extremely simple answer (prepend a "-") in NsCDE's FAQ, which I (obviously) hadn't read in the first place.
I'd suggest to add that information to the Manual chapter for clarity.

5. Install Icon
I added some existing application entries to subpanels, but in one case I wanted to change the Name and Icon; although I could change those values in the Install Icon window, those changes were not saved and I eventually had to edit the files $HOME/.NsCDE/NsCDE-Subpanels.conf and $HOME/.NsCDE/Subpanels.actions manually.
I wonder whether this is the intended behavior, or a small bug, or I just missed something.

6. $HOME/.NsCDE/Subpanels.actions
After subpanels customization with "Install Icon", I noticed that this entry
S8,Entry,PCManFM,,NsCDE/32x32/apps/system-file-manager.png,pcmanfm --no-desktop
which is present in file /opt/NsCDE/config/Subpanels.actions, had disappeared from $HOME/.NsCDE/Subpanels.actions
(maybe because its "Entry" keyword is not uppercase, like all the others in that file?)

7. Compositing Manager and Fvwm window resize/remove
I noticed that if a compositing manager is running, Fvwm doesn't show the 'X Y' coordinates box while moving a window, or the 'Width x Height' box while resizing a window; since there's already a paragraph in the Manual about compositing manager, maybe this information could be added.

**Comment by NsCDE** [comment]
Hi @leoctrl 

Thank you for your valuable input. There are really hepful things here. I will answer in order:

1. Indeed, this is set by nscde_setup on the 1st run blindly and it doesn't have any sense if CDE palette with 4th colorset is set which has black foreground and light background, like Crimson for example. This is also true for GTK2 gtkrc config. I have an idea how to remove this from nscde_setup and make Color Style Manager to handle it, based on the colorset 4 (usually text background). If switching back from NsCDE, like from any other env which is actually editing settings.ini or .gtkrc-2.0, user will really have to handle this by config of the next/new choosen window manager or desktop environment. This goes on TODO list.

2. Please tell me what version of the MX Linux. MX Linux was until now not on the list of virtual machines on which I have tested NsCDE. I never saw such flickering. Thanks for pointing to the right place in GTK3 CSS, usually it is hard to work with that mess. Except already mentioned Geany, please mention also some other examples, so I can try this myself.

3. Again, I didn't had such case till now. Thanks for info and workaround example. I should take care of this.

4. Ok,

5. I will examine this. This has beed worked. If it is on the same panel as PCManFM, maybe it is consequence of this typo. It happened like that in the past with some other typo there.

6. Indeed. A typo. I have fixed this and pushed. This one was trivial.

7. I have rarely used X compositor. Really, I never saw that this box is missing in that case. I will add a sentence about this.

Again, thank you for this extensive report!

**Comment by leoctrl** [comment]
Hello again,
thanks a lot for your prompt response; to answer your questions:
2. I'm using the latest stable MX version which, at present, is 19.3, in turn based upon the latest Debian Buster; Gtk3 version is 3.24.5. The Geany text editor is a Gtk3 application I regularly use and has a wide toolbar, so the horizontal flickering was particularly evident there, another Gtk3 application in which I noticed the same behavior is the Liferea feed reader. (but I guess any Gtk3 application with several buttons in its toolbar will do)
5. I will recheck with the new Subpanel configuration files modified for 6. and let you know.
Cheers

**Comment by leoctrl** [comment]
All right, as promised I replaced version 1.1 with the latest one (commit 79ff1d6 on 1st March), created a new test user, then retested the Install Icon function, and I'm happy to inform you that, as I suspected, the problem I've been experiencing was not with NsCDE, rather it was me who was missing something.
I found out that in order to change Name, Command or Icon I have to do the following:
1. select an Available Application from the left pane
2. change its value(s) in the bottom fields as desired
3. click the '>' icon to add it (as modified) to the Existing Items
4. Save
I noticed that if I enter an application Name, Command and Icon in the bottom fields without selecting an Available Application first, I can't add it to the Existing Items; that is, if I want to add an application that's not in the Available list I have to choose one from that list anyway, then change all of its values.
If I'm right, then I'd just suggest to describe this procedure in the relevant Manual chapter for clarity.
Thanks

**Comment by NsCDE** [comment]
Thanks @leoctrl for very detailed report. Install icon dialog is really a bit confusing and it is replacement for missing drag and drop functionality from some compatible file manager, which will be a total mimic of the CDE behaviour. I will for sure try to describe this more detailed in docs, and possibly make initial empty selection functional for adding a custom entry.
Leaving this open, because there are multiple issues here which I have to look this days.

Thanks.

**Comment by NsCDE** [comment]
Hi @leoctrl 

You can try current master tree.

1. Shutdown reboot and the rest should work ok now if you install and edit for your user /opt/NsCDE/share/doc/examples/sudo/006_PowerManager into /etc/sudoers.d for compatibility.
2. Button check and active error: I have been able to reproduce it in VM and I have tuned padding to be the same in the all directions. This solves flickering.
3. Dark theme: it can be removed by choosing palette which has light color 4 with black foreground for font, or by deselecting gtk2/gtk3 integration in Color Style Manager and pressing save.

The rest of your observations are also been fixed or documented.

**Comment by leoctrl** [comment]
First of all, thanks an awful lot for taking my feedback into serious consideration and intervening so quickly, I'm really impressed.
That said, I tested the latest version (commit a5803b9 on 5 March) and I confirm that /opt/NsCDE/libexec/nscde-acpi and $HOME/.themes/NsCDE/gtk-3.20/widgets.css now work out or the box for me.
As for $HOME/.config/gtk-3.0/settings.ini, I logged in as a brand new test user and started NsCDE accepting all default settings, including the Broica color scheme; that file was created from scratch and included 'gtk-application-prefer-dark-theme = 1',
From your notes I understand that's because Broica's 4th color is a Dark Grey; therefore, I selected a different scheme, i.e. Solaris, whose 4th color is white, and rechecked that file: setting 'gtk-application-prefer-dark-theme' was no longer present.
I presume this is also working as you meant it to, so I'd just suggest to mention the management
and, most importantly, effects of that file's settings in the Manual and FAQ for the benefit of those who, as it happened to me, might inadvertently switch from NsCDE to another desktop environment only to find any Gtk theme they choose always switching to its dark variant, no matter what. 
Cheers

**Comment by NsCDE** [comment]
This with dark theme in GTK is a tricky thing. If this hint is not in place, and text area and field like widgets are dark, this can prevent dark-on-dark or white-on-white situations in number of applications and cases. So when used with CDE palette which has a dark color 4 (definition of dark is when automatic foregraound is white, not black) I need to ensure the best possible and least buggy behaviour with GTK2/3.
Unfortunately, if someone switches out from NsCDE, gtk-application-prefer-dark-theme remains in ~/.config/gtk-3.0/settings.ini and ~/.gtkrc-2.0 and can cause strange effect.
Yes, I will document this and put in FAQ, this is what I can really do.
