### ISSUE TITLE
Alot of things does not execute on freebsd

### ISSUE THREAD

**Issue by agoodfellow123** [NsCDE/NsCDE#48]
Hello there i installed nscde with [this guide](https://forums.freebsd.org/threads/amazing-fvwm-cde-clone.71965/) on freebsd with minor modifications (such as python version). My problem is programs such as the terminal, firefox, alacritty, callendar, file manager, print manager, some of the options in style manager (not all), text editor, multimedia, help, etc... does not execute when pressed on panel or called from Exec.

**Comment by NsCDE** [comment]
Hello

This is old and non-official. Please read official documentation and [FAQ](https://github.com/NsCDE/NsCDE/wiki/NsCDE---Frequently-Asked-Questions-(FAQ)). Search for "freebsd".

What you described smells like you don't have real Korn shell installed on the system.

This is `pkg info` from my FreeBSD VM:
`ast-ksh-20141224_1             KornShell 93`

Check this first, and check that you use the latest release (1.1). You can also clone master tree which goes for 1.2 soon.

**Comment by agoodfellow123** [comment]
Installed [ksh93](https://svnweb.freebsd.org/ports/head/shells/ksh93/). NsCDE version is 1.2. I also installed everything listed below freebsd in faq. Everything is the same.

**Comment by NsCDE** [comment]
Strange.

Do you have "ksh93" as a binary or link available in your $PATH? What is the contents of the ~/.xsession-errors?

**Comment by agoodfellow123** [comment]
Yes ksh93 is in $PATH but there is no file named ~/.xsession-errors.

**Comment by agoodfellow123** [comment]
Re installed from scratch with recommended settings, sadly it wants some python packages that i already have and pip cannot install them. [Here](https://i.ibb.co/tqW0n7m/fewawaca.png) is the picture.

**Comment by NsCDE** [comment]
PyQt4 is very old, but supported as alternative for PyQt5. It will be tried if PyQt5 is not found. Install PyQt5, you will probably not found PyQt4 either.

As seen on the picture, you need also py37-xdg, py37-psutil. Use FreeBSD pkg to install. Everything needed as dependency can be installed from package in my FreeBSD experience.

**Comment by agoodfellow123** [comment]
The problem is, i already installed py37-xdg, py37-psutil and py37-AnyQt. The installer cannot detect them.

**Comment by NsCDE** [comment]
What is the output of this commands?

`python3 -c 'import xdg'`

`python3 -c 'import psutil'`

`python3 -c 'import PyQt5'`

... this should be all empty outputs without errors.

See if they are really installed as normal FreeBSD packages:

pkg info | egrep 'py37-(xdg|psutil|qt5)'

**Comment by agoodfellow123** [comment]
They all give [errors](https://i.ibb.co/sjvGdP7/fea.png) but they also all [show up](https://i.ibb.co/8j60bnn/feaf.png) in egrep and when i try to [install them](https://i.ibb.co/sHQf336/feafe.png) they return "packages are already installed"

**Comment by NsCDE** [comment]
I see ...

Then only one thing still can be broken on your sistem, and that is "python3" binary, wrapper or symlink itself.

`which python3`
`ls -l /path/to/python3`
`python3 --version`

Maybe you have Python 3.9 or pre-3.7, but modules for 3.7 ...

**Comment by agoodfellow123** [comment]
Bingo! the version was returning 3.6 despite having 3.7 on the system. So i deleted that and re-installed python and reinstalled NsCDE. It booted fine with everything working except for the [application menu](https://i.ibb.co/cvp5spb/faawd.png) (i do have py37-xdg). Also, the resolution was wrong but im testing on a virtual machine for now so i assume that's normal. Still, if there is a way to correct that at startup please enlighten me.
Thank you for everything so far!

**Comment by agoodfellow123** [comment]
Also [these](https://i.ibb.co/T8q3y49/afwa.png) and multimedia me are broken too but to be honest i can live without them. So no problem.

**Comment by NsCDE** [comment]
Check py37-xdg ... it is probably deinstalled while you were reorganizing the system. :)

For a resolution in VM, I usually put this into ~/.NsCDE/Xset.conf:
`xrandr -s 1920x1080`


Your last screenshot does not indicate error, but simply information that you can write this functions into your ~/.NsCDE/NsCDE-Functions.local to call something useful when clicked. Like thunderbird for example. You should already have example of that file in ~/.NsCDE.

P. S.
Try to reduce font size a bit, or check your DPI settings with xrandr.

**Comment by agoodfellow123** [comment]
Hmm.. removed and re installed py37-xdg, doesn't seem to change anything. Font fixed itself after xrandr thanks!

**Comment by NsCDE** [comment]
Strange. You can always test if python3 sees xdg with `python3 -c 'import xdg'`. Also, check which python is calling /usr/local/bin/fvwm-menu-desktop as hashbang on the first line. Maybe it is a different one and needs to be set. Python compatibility is a real mess last years, and FreeBSD just adds even more to this unfortunately.

**Comment by agoodfellow123** [comment]
`python3 -c 'import xdg'` returned nothing, which is good i believe. fvwm-menu-desktop has 3.7 which is also good.

**Comment by NsCDE** [comment]
Ok, I would say this is not anymore NsCDE issue. Find what is preventing fvwm-menu-desktop from finding xdg and you are probably all set up. :)
