### ISSUE TITLE
The Curious Case of Caja's Dual Pane

### ISSUE THREAD

**Issue by leoctrl** [NsCDE/NsCDE#49]
Hi again,
I'd like to report another very small thing I noticed.

Premise
Caja is a Gtk3 file manager (part of the Mate Desktop Environment) whose default layout is a classic single pane + sidepane on the left, but its single pane may be optionally split vertically into a dual pane; as for its available view modes, they are large icons ("Icon View"), small icons ("Compact View"), and detailed list ("List View").
When items are selected in List View, $HOME/.themes/NsCDE/gtk-3.20/widgets.css inverts their color, i.e. 'background-color' becomes '@fg_text', and 'color' in turn becomes '@bg_text'.

Small Thing I Noticed
Having split the pane, chosen List View in one of the panes, and selected one or more items in that List View pane, if you click on the other pane the previously selected item(s) disappear.
By "disappear" I mean that it looks like the 'background-color' property is reset to '@bg_text', but not the 'color' property, making the text indistinguishable; only the icon(s) remain visible.

Quick and Dirty Workaround
First, I checked that this happens only with the NsCDE Gtk theme; having done that, I went through $HOME/.themes/NsCDE/gtk-3.20/widgets.css to try and find out which selector/property springs into action when you click on the other pane, but that file is really HUGE and my knowledge of CSS really limited, so eventually I gave up.
As a quick and dirty workaround I created a very simple $HOME/.config/gtk-3.0/gtk.css to just reinstate the selected items color, like so

.caja-notebook treeview.view:selected,
.caja-notebook treeview.view:selected:focus {
    background-color: @fg_text;
    color: @bg_text;
}

This way they just don't disappear anymore ;-)

I'm posting this FYI, just in case it may help.
Cheers

**Comment by NsCDE** [comment]
Hi @leoctrl 

Thanks for this detailed info and pointers of how to handle this situation.

As before, I will take a look how to incorporate this in a more generic way that is not one-app-only setup. Otherwise, this can be Caja-only workaround for a FAQ.

I must test this and see ...

**Comment by leoctrl** [comment]
Well, I'm embarrassed...
By sheer coincidence, today I found the time to recheck this thoroughly in Xfce, and I'm happy to inform you that it may happen also in that Desktop Environment, depending on the chosen Gtk3 theme.
In other words, contrary to what I initially thought, it doesn't seem to be strictly related to NsCDE's Gtk3 theme.
I was just about to admit that I raised a false alarm, but your response came first.
I'm sorry for having wasted some of your time.
Thanks

**Comment by NsCDE** [comment]
Hi,

By trying this yesterday, I'm able to reproduce this behaviour, and I have noticed that with some themes, we get this kind of behaviour, and with some we don't. It looks like treeview.view:selected causes this, not treeview.view:selected:focus, but even more interesting is that your workaround works when it is in ~/.config/gtk-3.0/gtk.css, with and without .caja-notebook prefix, but it does not work if put directly into ~/.themes/NsCDE/gtk-3.20/widgets.css anywhere.

I cannot determine which error is this: caja, gtk3, or NsCDE and some other themes. I will try to dig a bit into this before 1.2 release, but it may end up as gtk.css workaround for Caja only. Maybe to ask MATE people ... we will see ...

**Comment by NsCDE** [comment]
It looks like this depends on color lightness calculation. For some themes it works, for some not. Nothing I can do about it. What remains interesting is how the same CSS code works from ~/.config/gtk-3.0/gtk.css, but it doesn't from ~/.themes/NsCDE/gtk-3.20/widgets.css no matter where I position this.
