### ISSUE TITLE
[Suggestion] make last system action saving optional

### ISSUE THREAD

**Issue by leoctrl** [NsCDE/NsCDE#51]
Hi, it happened to me several times to shut down the system, whereas I just wanted to log out from NsCDE, just because I had shut it down the day before, so "Shutdown" was the last system action saved in $HOME/.SysActionDialog.lastval, and I inadvertently clicked "Confirm" without choosing the "Logout" action from the drop-down list first.
I have therefore taken the liberty of modifying /opt/NsCDE/lib/scripts/SysActionDialog so that $HOME/.SysActionDialog.lastval is always set to 1 (Logoff); this way, if I want to do something different, I have to choose it explicitly from the drop-down list, and that's perfectly fine for me.
Maybe there are other NsCDE users who would prefer such behavior, so I thought that the Logout dialog could be enriched with some sort of "Remember last action" checkbox.
This is a just a simple suggestion based on a personal experience, if you think it's not worth adding it to the ToDo list for the next release I'll understand.
Thanks

**Comment by NsCDE** [comment]
Good point. I think I will go to with the checkbox solution that you suggested.

**Comment by NsCDE** [comment]
Done. You can test it.
