### ISSUE TITLE
volume/brightness keys and laptop closing

### ISSUE THREAD

**Issue by oolosunde** [NsCDE/NsCDE#52]
As a laptop user, it was quite frustrating to find that this didn't work with my volume or brightness keys. Also, my laptop doesn't lock when I close it. Closing it seems to just turn the screen off.

**Comment by NsCDE** [comment]
Hi,

On my laptop, hw backlight keys are working. Independent of the system. Volume Keys should work ok, try to catch keypresses on volume keys with xev(1). They should be called "XF86AudioLowerVolume" and "XF86AudioRaiseVolume". It would also help to indicate what Linux or BSD system you are using.

Last, suspend on laptop lid down is usually controlled by the system, not DE.

**Comment by NsCDE** [comment]
Since this is not NsCDE nor fvwm problem, and there is no new feedback, I'm closing this one.
