### ISSUE TITLE
Problem with web apps

### ISSUE THREAD

**Issue by farzadfusion** [NsCDE/NsCDE#55]
I have been using NsCDE for 1 month now and I can say all the web-apps such as slack, Skype,  and Spottily work with delay. 
For instance, in the case of Slack, the apps get suspended and then the message is delivered after 10 seconds or for the case of Spotify I change the music or volume but it takes few second for it to take place. This might be due to Electron Javascript library that is not working efficiently with NsCDE but if this problem is resolved, this will become a very useful desktop environment. 

Thanks for all the hard work and got to say I love this.

**Comment by NsCDE** [comment]
Hi @farzadfusion 

Just to distinguish NsCDE and FVWM problems with various potentially troublesome apps: does this apps work ok in vanilla FVWM setup? How about under some other WM? Is this really WM problem? I don't see how it can be.

Personally, I use 2-3 electron apps and they seems to be ok.
