### ISSUE TITLE
Strange VirtualBox GUI behaviour

### ISSUE THREAD

**Issue by leoctrl** [NsCDE/NsCDE#57]
Hi, I like the Broica 4 colour scheme a lot, but there's one application that seems to dislike it: the VirtualBox GUI (see screenshot)

![Broica](https://user-images.githubusercontent.com/76251840/122581189-1354f880-d057-11eb-86f2-b57b08282f03.png)

I guess that's because of Broica's white text, because using a theme with black text (e.g. Solaris) the same window looks fine.

![Solaris](https://user-images.githubusercontent.com/76251840/122581596-81012480-d057-11eb-86d4-65d1311c0c2f.png)

It's not a big problem, just a bit of a nuisance: whenever I want to use VirtualBox I have to either switch theme or switch Desktop Environment, but anyway I'm curious: why is this happening? As far as I know, VirtualBox' GUI is based on Qt, and all other Qt-based applications I use (KeePassX, qBittorrent, Vlc, etc.) look perfectly fine with Broica.
Is there anything you can suggest?
Thanks

**Comment by leoctrl** [comment]
Hi again, while trying to investigate this strange behaviour further, I stumbled upon this bug report
https://www.virtualbox.org/ticket/18258
As you can see from the screenshots attached to that, it's a problem very similar to the one I'm experiencing, and I confirm that passing command line option "-style Fusion", as suggested in that thread, solves it (for me, at least)

![Broica-fixed](https://user-images.githubusercontent.com/76251840/122664317-02180300-d1a1-11eb-9635-12d5fd5f2711.png)

No need to switch theme or DE any longer!
Even though it's clearly a VirtualBox issue, maybe mentioning this in NsCDE's documentation or FAQ might help someone.
Thanks

**Comment by NsCDE** [comment]
Hi leoctrl,

My thinking is: same issue as some other apps: forcing background color to be different from theme widget type, but forgotting the foreground, that is, text color. Then we get white on white or black on black. Nothing I can do here generally, but there are only workaounds on per app basis.

Yes, I should mention this in chapter for theme integration and in the FAQ, thanks.
