### ISSUE TITLE
couldint install nscde on void linux becauce cpp is not avalible in the repo

### ISSUE THREAD

**Issue by brockthefox** [NsCDE/NsCDE#58]
so i tried installing Nscde on Void Linux ived tried installing it but i cant because i get this error message " Error: command or program "cpp" as NsCDE dependency is missing.

Error: Missing required commands or packages: cpp. Install them and run Installer.ksh again" i tried to install cpp but i cant find it any where in the repo but if you know how to install cpp on void let me know.

**Comment by drscream** [comment]
You can find `cpp` in the `gcc` package. I hope that helps you to install NsCDE.

**Comment by brockthefox** [comment]
thanks but when i hit the reboot or shutdown button in NsCDE it take me back to the login screen
