### ISSUE TITLE
[suggestion] allow whitespace in X11 Class/Resource Name in the Geometry Manager

### ISSUE THREAD

**Issue by leoctrl** [NsCDE/NsCDE#59]
Hi,
while investigating VirtualBox' GUI strange behaviour (issue #57) I noticed something else: the Geometry Manager refused to save the window size and position, due to a whitespace in the Class and Resource Names (as a matter of fact, both identify themselves as "VirtualBox Manager")
Having seen that both scripts confget.py and confset.py in /opt/NsCDE/bin make use of Python's configparser which, according to its documentation, supports whitespaces in keys, I tried to manually editing $HOME/.NsCDE/GeoDB.ini and added a line, like so:

> VirtualBox Manager,VirtualBox Manager = (width)p (height)p (x-pos)p (y-pos)p

It worked; I made several experiments modifying the 4 values in $HOME/.NsCDE/GeoDB.ini, and every time the VirtualBox' GUI window did comply with the settings. So, I've taken once again the liberty of modifying /opt/NsCDE/lib/scripts/GeometryMgr slightly, in order to accept and save X11 Classes and Resources with whitespaces in their names.

I've attached my patch, just to give you an idea of what I did
[allow_whitespaces_in_x11_class_and_resource_names.patch.txt](https://github.com/NsCDE/NsCDE/files/6682490/allow_whitespaces_in_x11_class_and_resource_names.patch.txt)

However, if you think that such modification would be inappropriate (e.g. may have undesired side effects) do feel free to discard my suggestion.
Thanks

**Comment by NsCDE** [comment]
Hi @leoctrl 

I have managed to test this. Thanks. Applied to master.
