### ISSUE TITLE
UI glitch after fixed suspend support

### ISSUE THREAD

**Issue by rtomsick** [NsCDE/NsCDE#6]
So unfortunately, the fix for issue #5 appears to have broken the dialog slightly.

As of `9fe7dc0493`, the value of the drop down does not appear to be updated when a selection is made.  

Making a selection and pressing "Confirm" still works, and indeed upon bringing up the dialog again the drop-down now displays the previous selection.  This behavior is not observed when making a selection and pressing "Dismiss".

**Comment by NsCDE** [comment]
It was like that before. Previous choice will be recorded only on "Confirm", Dismiss, Cancel and such buttons actions should not modify anything generally.

**Comment by rtomsick** [comment]
Ah, I think I may have muddied the waters and confused things when describing the issue. Sorry!

I understand the Confirm vs. Dismiss behavior (confirm makes the selection the default the next time the dialog is displayed.)

The behavior that I think is wrong is that when the dialog is open, when a selection is made from the drop-down, the displayed value in the selection control is not updated.  Specifically:

1. Open the "System Action" dialog.  Make a note of the operation displayed in the selection control.
2. Click the selection control to display the drop-down menu.
3. Make a selection other than the one displayed in step 1. The menu will disappear when the selection has been made.
4. Observe the value now displayed in the selection control.

In most (all?) windowing toolkits, the value in step 4 would reflect the selection made in 3.  Windows, Mac OS (and macOS/OS X), iOS, Motif, GTK, and Qt all work this way.  But in the case of this dialog, the value in step 4 will always be the same as observed in step 1.

I don't remember it being this way when I first used NsCDE, but maybe it was... either way, I think this behavior should be changed to be consistent with the way that drop-down selection inputs work elsewhere.  I think it will confuse users coming from other environments -- I know it certainly confused me!

**Comment by NsCDE** [comment]
If I understood you correctly, you want to say that when you change selection from the drop down menu, and close drop down menu, you don't see new value displayed, but the old one?

I know you are using Fedora 31, so I tried that in VM on Fedora 31 and default fvwm rpm which
comes from their repos. I cannot reproduce behaviour you described here. My selection is updated every time. Tried 10+ times.

Try with Up/Down cursor keys and see if there is any difference.

If this is really the case, try to refresh the screen after you made the selection. I don't know, maybe display is not updated?

See if Num Lock is turned on ... this can be source of many strange cases.

**Comment by rtomsick** [comment]
Up/Down cursor keys work fine, with the selection updated immediately after key press.

`~/.NsCDE/.SysActionDialog.lastval` does not appear to be updated when the value is changed w/ the mouse while the dialog is displayed (i.e. when I am simply picking different entries, but not pressing "Confirm" or "Dismiss".)  This value IS updated when a selection is made (w/ either mouse or keys) and "Confirm" is pressed.

So it looks like it's specific to mouse interaction w/ the control?

**Comment by rtomsick** [comment]
Just in case this is necessary for repro...

```
Name         : fvwm
Version      : 2.6.9
Release      : 2.fc31
Architecture : x86_64
---
Name         : xorg-x11-server-Xorg
Version      : 1.20.5
Release      : 8.fc31
Architecture : x86_64
---
```

**Comment by NsCDE** [comment]
That's ok, choice number in ~/.NsCDE/.SysActionDialog.lastval is updated only when confirm button is clicked and action performed.

Rob, I'm still not able to reproduce what you are saying here. I have tried in KVM on Fedora 31 with this versions of fvwm and xorg, with fully updated, tried on FreeBSD, Arch Linux and CentOS 7 (hardware). Fvwm 2.6.8, 2.6.9 ... nothing, nil. I cannot reproduce the situation when something is changed in popdown menu that old value is immediately back to prior one when dialog is opened. When I do suspend, logout or restart and click confirm, that "lastval" remains.

Please inspect your local setup. Maybe you have some overlay which is messing your X server, some extension, bad mouse or xset mouse parameters, VNC ... I don't know what this can be, and cannot get that behaviour at least once to manifest itself.

**Comment by rtomsick** [comment]
So... you may well crucify me for this (and I wouldn't blame you!) but.... I realized I was only testing this w/ `compton-ng` running!  I didn't have any shadows enabled, so it didn't occur to me it had been running until I was reviewing my XDG autostarts...

Sorry! I feel like an idiot...

I can't easily retest w/o it at the moment as I'm away from that machine, but in case that was required for repro, here's the config I was running:

```ini
# Shadow
shadow = false;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;
#log-level = "debug"
log-level = "warn"
# log-file = "/path/to/your/log/file";
# shadow-opacity = 0.7;
# shadow-red = 0.0;
# shadow-green = 0.0;
# shadow-blue = 0.0;
shadow-exclude = [
	"name = 'Notification'",
	"class_g = 'Conky'",
	"class_g ?= 'Notify-osd'",
	"class_g = 'Cairo-clock'",
	"_GTK_FRAME_EXTENTS@:c"
];
# shadow-exclude = "n:e:Notification";
# shadow-exclude-reg = "x10+0+0";
# xinerama-shadow-crop = true;

# Opacity
#inactive-opacity = 1;
# active-opacity = 0.8;
#frame-opacity = 1;
#inactive-opacity-override = false;
# inactive-dim = 0.2;
# inactive-dim-fixed = true;
# blur-background = true;
# blur-background-frame = true;
#blur-kern = "3x3box";
# blur-kern = "5,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1";
# blur-background-fixed = true;
#blur-background-exclude = [
#	"window_type = 'dock'",
#	"window_type = 'desktop'",
#	"_GTK_FRAME_EXTENTS@:c"
#];
# opacity-rule = [ "80:class_g = 'URxvt'" ];

# Fading
fading = false;
# fade-delta = 30;
#fade-in-step = 0.03;
#fade-out-step = 0.03;
# no-fading-openclose = true;
# no-fading-destroyed-argb = true;
#fade-exclude = [ ];

# Other
#backend = "xrender"
backend = "glx";
mark-wmwin-focused = true;
mark-ovredir-focused = true;
#use-ewmh-active-win = true;
detect-rounded-corners = true;
detect-client-opacity = true;
refresh-rate = 0;
vsync = true;
#sw-opti = true;
unredir-if-possible = true;
# unredir-if-possible-delay = 5000;
# unredir-if-possible-exclude = [ ];
detect-transient = true;
detect-client-leader = true;
#invert-color-include = [ ];
# resize-damage = 1;

# GLX backend
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
#xrender-sync-fence = true;
#use-damage = true;

# Window type settings
wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 1; focus = true; full-shadow = false; };
  dock = { shadow = false; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 1; shadow = false; }
  dropdown_menu = { opacity = 1; shadow = false; }
};
```

And the package info:

```
Name         : compton-ng
Version      : 7.4
Release      : 1.fc31
Architecture : x86_64
Source       : compton-ng-7.4-1.fc31.src.rpm
Repository   : @System
From repo    : fedora
```

**Comment by NsCDE** [comment]
Ha ha ha. So it turns it WAS a overlay for X ... in the form of the standalone X renderer. I'm glad we now know what was that.

I didn't tried compton-ng till now, but with plain compton, several months ago, I had a similar glitch with plain classis menu of some GTK app: when I clicked "File" or "Edit" it seamed that no drop down menu was there. It **was**, but it was not visible, not rendered. Killing compton which was turned on for testing, removed that behaviour. So it is not only FvwmScript in which GUI parts of NsCDE are written, but GTK and probably most of what is on the display can have this glitch.

It is a compton or Xorg thing. Thanks for the config. I have tried now with this config and plain /dev/null as --config argument. Both, compton and compton-ng will trigger this behaviour. Refresh from the left titlebar button of the window will uncover what is selected on menu. I can ask FVWM people if some X refresh workaround can be deployed, but this is probably something for compton developers to consider.

Ok, rc15 time this week. It will be one year since I started NsCDE development this friday. :-)

**Comment by rtomsick** [comment]
I know, I feel like an idiot for not remembering that!

Whatever the bug, in this case it seems to be somewhat FVWM specific, since the behavior is not present w/ GTK or Motif drop-downs or context menus, even w/ compton or compton-ng running.

I wonder if there are some compton(-ng) flags that might affect this?

Either way, not your bug.  Thanks, and sorry for the trouble! :)
