### ISSUE TITLE
NsCDE changes system appearance of other desktop environments.

### ISSUE THREAD

**Issue by novaTopFlex** [NsCDE/NsCDE#60]
With NsCDE (on Ubuntu 20.04 LTS), the system appearance in applications changes to resemble that of NsCDE, even when I start a session with a different desktop environment. Why is that?

**Comment by ThomasAdam** [comment]
Hi @novaTopFlex 

Because NsCDE sets the GTK preferences for ALL GTK applications.

**Comment by NsCDE** [comment]
@novaTopFlex 

Because NsCDE integrates GTK and Qt theme for unified experiance. Nothing you cannot change back with appereance settings of another DE or by editing ~/.gtkrc-2.0 and ~/.config/gtk-3.0/settings.ini manually to get another GTK2 and GTK3 themes.
