### ISSUE TITLE
X Display Manager (XDM) wont boot into NsCDE

### ISSUE THREAD

**Issue by brockthefox** [NsCDE/NsCDE#63]
![VirtualBox_Void Linux_24_07_2021_18_10_03](https://user-images.githubusercontent.com/38122451/126882535-14dbba22-2341-4cec-b162-4bf7cb098510.png)
![VirtualBox_Void Linux_24_07_2021_18_26_23](https://user-images.githubusercontent.com/38122451/126882536-62b68d83-36c4-41d0-8d82-994d58eec409.png)
So i have done a fresh base install of Void Linux in a Virtualbox and i decided to pick the X Display Manager (XDM) because it is the most retro looking login manager that goes perfectly well with NsCDE but when i tried to bootup the VM the XDM login screen does show up but when i tried to login it doesn't boot into NsCDE it just takes me to the terminal screen, but i tried to find some tutorials how to get XDM to boot into the Desktop Environment/Window Manager but i cant find any tutorial or any documentation how it setup to log into the Window Manager (NsCDE) but if you know how to get XDM to log into NsCDE please show me step by step how to get it working thank you.

**Comment by NsCDE** [comment]
Hi

Have you tried with

`exec /opt/NsCDE/bin/nscde`

in user's ~/.xsession or ~/.xinitrc?

This rc files in $HOME should be read by XDM. XDM does not handle .desktop files in /usr/share/xsession.
