### ISSUE TITLE
Switching back to NsCDE TTY stops monitor output

### ISSUE THREAD

**Issue by DouglasDC-3** [NsCDE/NsCDE#65]
Hello

If I recall correctly. I could simply start NsCDE (by default it was CTRL ALT F7) then switch to CTRL ALT F6 then startx to run MAXX Interactive Desktop so I could use both at once.

For some reason it doesn't work anymore. When I switch tty terminal back to NsCDE the monitor output ceases and my CRT monitor goes offline mode.

I am in Debian Unstable and here are my Specs

Phenom 9750 - GeForce 8200 - 2x2 DDR2 - Nouveau Drivers -LightDM

Since my setup is rather old it's probably not worth investigating if it can't be verified on your end but I thought maybe it happens on your setup too.

**Comment by DouglasDC-3** [comment]
did some more testing

it doesn't happen during normal usage. I use discord to watch someones stream and when i make startx tty at f6 then switch back to nscde it works. but if i do repeatedly and foget to release ctrl and alt keys nscde tty makes monitor no signal

**Comment by NsCDE** [comment]
Hi,

This is a system and Xorg server issue. It is very unlikely FVWM and even less NsCDE has anything with this. See your xorg server logs and dmesg.
