### ISSUE TITLE
(request)Is there an way to theme NsCDE to look more modern?

### ISSUE THREAD

**Issue by Lixkote** [NsCDE/NsCDE#82]
Is there an way to theme NsCDE to look more modern?
Or is there an way to apply any (modern looking)themes to it?

**Comment by damon-kwok** [comment]
Hi, @Lixkote 
`NsCD` is the kind of `DE` that deliberately pursues `retro style`. 
If you like `modern` DE, I recommend you to use [Enlightenment](https://github.com/Enlightenment)

**Comment by Lixkote** [comment]
But is there any modernized version of cde?

**Comment by Lixkote** [comment]
I Want an Cde (yes, exacly cde) but with themes support and papirus icons.

**Comment by Lixkote** [comment]
I tried enlightment but i doesnt fit into my needs

**Comment by NsCDE** [comment]
Hi Lixkote

As said above, and as you can read in README.md, NsCDE is anti-modern as it can be. It is backwards and anti-progress. :-)
This is the very LAST DE from you can expect modernity.

Altrough, you can make your own color schemes for Color Style Manager which looks "modern" (whatever that means to someone), use wallpapers from Backdrop Style Manager instead of backdrops, and you can edit ~/.NsCDE/Xsettingsd.conf to
Net/IconThemeName set to Papirus or whatever, same in qt5ct, and you are all set.

**Comment by Lixkote** [comment]
> Hi Lixkote
> 
> As said above, and as you can read in README.md, NsCDE is anti-modern as it can be. It is backwards and anti-progress. :-) This is the very LAST DE from you can expect modernity.
> 
> Altrough, you can make your own color schemes for Color Style Manager which looks "modern" (whatever that means to someone), use wallpapers from Backdrop Style Manager instead of backdrops, and you can edit ~/.NsCDE/Xsettingsd.conf to set Net/IconThemeName to Papirus or whatever, same in qt5ct, and you are all set.

Any chance of changing window border style? And when Custom Styles wiki be available?

**Comment by Lixkote** [comment]
And @NsCDE Thanks for replying! :+1:

**Comment by NsCDE** [comment]
> Any chance of changing window border style? And when Custom Styles wiki be available?

This is not so much NsCDE domain of things anymore, but my framework and upstream - FVWM.

See "Style" command in fvwm(1).

In NsCDE, you can override FVWM styles (titlebars, borders) by writing local extension or override of Style configuration of NsCDE. See documentation for 2.x - fvwmconf, fvwmgen and fvwmlocal files.

That way, you can build on the top of NsCDE, or even one day use NsCDE as a starting point for your own FVWM based DE.

**Comment by Lixkote** [comment]
Thanks!

**Comment by Lixkote** [comment]
@NsCDE And one last question: where are Fvwm files located like fvwmconf?

**Comment by NsCDE** [comment]
2.0 source: data/fvwm

1.X source: NsCDE/config

**Comment by Lixkote** [comment]
Thanks

**Comment by Lixkote** [comment]
@NsCDE Sorry, but can you guide me how to change Fvwm styles? 
Sorry, but I'm too stupid to understand this :(

**Comment by NsCDE** [comment]
This is not straightforward. Search BorderWidth style in manual page of fvwm, google for FVWM and fvwm styles, read docs on https://www.fvwm.org/ ... there are resources online. The learning curve is not straightforward, and things cannot be mastered in a few minutes. It requires a bit of reading.
