### ISSUE TITLE
NsCDE fails to execute in Sparky Linux

### ISSUE THREAD

**Issue by Mach28** [NsCDE/NsCDE#83]
NsCDE is failing to start in new install Sparky 6.1 or 7 due to the login error: "Xsession: unable to launch  "/opt/NsCDE/bin/nscde" X session --- "/opt/NsCDE/bin/nscde" not found". But the executable seems to be in /opt/NsCDE/NsCDE/bin/ instead.

**Comment by damon-kwok** [comment]
Hi, @Mach28 
- you can commit issues to `Sparky Linux` community:
https://github.com/sparkylinux

- You can also try to install manually：
https://github.com/NsCDE/NsCDE/blob/master/INSTALL.md
``` sh
sudo apt update
sudo apt dist-upgrade
sudo apt install -y ksh xutils/x11-utils xdotool imagemagick \
    xscreensaver x11-xserver-utils python3-yaml python3-pyqt5 \
    qt5ct qt5-style-plugins stalonetray xterm python3 \
    python3-xdg libstroke0 xsettingsd fvwm fvwm-icons \
    libfile-mimeinfo-perl gkrellm rofi xclip
```

**Comment by NsCDE** [comment]
Yup, this is clearly the mistake of package on Sparky Linux.

You can try NsCDE 2.0 which will be released in the next week or so.

mkdir deb_build
cd deb_build
git clone https://github.com/NsCDE/NsCDE.git
mv NsCDE nscde-2.0
cd nscde-2.0
ln -s pkg/debian
debuild -uc -us -b
cd ..
apt install ./nscde_2.0-6_amd64.deb

I will have to prepare new wiki for installation of 2.0 and migration.

**Comment by Mach28** [comment]
Thanks for that info. I will report the problem to SparkyLinux. 

I went on and installed v. 2.0 and it's working with a few quirks. For example, I moved the mouse quickly to the right and the open windows disappeared. When Iogged out and back in the terminal was back.  

There also seems to be a errant square box on the lower right along the bottom (about the height of the dock) that had  a speaker icon in the lower right corner which activates an audio volume slider. I tried to close it but the speaker icon disappeared but the box remains even after rebooting and restarting NsCDE.  I'm also sorry to report that the system keeps locking up on me, at least temporarily, the last time after launching WatchErrors. FYI, this is all in a VM.

**Comment by NsCDE** [comment]
Hi @Mach28 

You reported here a couple of things ... let's go one by one ...

1. The "errant square box" is a stalonetray(1) it is there if it is enabled with nscde_use_stalonetray in ~/.NsCDE/NsCDE.conf. Volume slider inside is obviously pnmixer. If you don't have many tray programs, or don't want it, disable stalonetray in above mentioned conf file.
2. By "system keeps locking on me" you mean xscreensaver appears and locks the screen (nscde_use_xscreensaver in ~/.NsCDE/NsCDe.conf) or the OS freezes, or mouse pointer turns into sand clock? In the later case, some errant function is "Wait"-ing (FVWM Wait command) for something which never appears. Pressing Ctrl+Alt+Escape 5-6 times should "unlock" this as a temporary solution. If OS freezes, this has nothing to do with NsCDE ... it is working VERY high and away from the OS internals.
3. During development, I'm testing this on Fedora 33 and Fedora 34, Debian 11, Ubuntu, MX Linux, Open Suse, Arch Linux, FreeBSD, NetBSD, OpenBSD, DragonFly BSD and OpenIndiana Solaris.
