### ISSUE TITLE
Html help documents images are missing

### ISSUE THREAD

**Issue by marcomto** [NsCDE/NsCDE#85]
I have an issue displaying the images in the new version of the html help documents.
When I 'sudo make install' the documents are copied from source folder to

	/usr/local/share/doc/nscde/html

but the img folder (or at least its symlink) is not created in the destination folder.
As a result, when I open the html help documents from the nscde subpanel (pointing to /usr/local/share/doc/nscde/html), the images are not displayed

![image_missing](https://user-images.githubusercontent.com/59309883/145689753-ad5dad8e-6c67-4ea0-b953-3a9566bacc2e.png)
.

**Comment by NsCDE** [comment]
Hello @marcomto 

Hahaha, you jumped in between two commits. This is VERY fresh. The first commit was a missing Makefile.am updates, fixed an hour ago. :-)

Fetch the changes and reset.

**Comment by marcomto** [comment]
Yes, it works with the last commit. Thank you very much. 
By the way, NsCDE is amazing :-)
