### ISSUE TITLE
NsCDE will fail to install on Ubuntu 20.04 and maybe newer

### ISSUE THREAD

**Issue by MrRocketFX** [NsCDE/NsCDE#86]
Failure will happen has the ksh package on Ubuntu doesn't have a ksh93 binary.
this can be a simple patch by copying the existing ksh binary after installing the package and making a copy called "ksh93"

**Comment by damon-kwok** [comment]
@MrRocketFX 
https://github.com/NsCDE/NsCDE/blob/master/INSTALL.md

**Comment by MrRocketFX** [comment]
I followed the guide but the ksh package does not supply a binary called ksh93 and I looked into it and it's not mentioned on the INSTALL.md unless I'm missing something then please point it out

**Comment by damon-kwok** [comment]
try:
``` sh
sudo ln -s /usr/bin/kash /usr/bin/kash93
```

**Comment by sunlitlaz** [comment]
Thank you, I had a problem with NsCDE not starting on Ubuntu 20.04 and this fixed the problem!

**Comment by NsCDE** [comment]
As I see in my virtual machine with Ubuntu, there is "ksh93" package installed and everything seems to be ok. Even deb
package that I create on Debian, installs on Ubuntu without problem.

Anyway, if I miss something here, this will be resolved for 2.1. I had to draw the line someware.

**Comment by espio999** [comment]
Hi

This is the case in Ubuntu 20.04.2.LTS on Hyper-V.

At first, "Known system specific package dependencies" misses followings in my case.

-dunst
-gettext (this is for msgfmt)
-ksh93
-libx11-dev (this is for cursorfont.h)
-libxext-dev (this is for shape.h)
-libxpm-dev (this is for xpm.h)
-python3-psutil

After installing these missing packages, "make" and "make install" was no problem.  Rebooting VM once, I got to the screen attached (I deleted user id from the picture).
Strangely, use can't login in NsCDE, though other GUI as MaXX and Ubuntu is ok.  Entering password, user is pushed back to the login screen.

![login](https://cdn-ak.f.st-hatena.com/images/fotolife/e/espio999/20211230/20211230174223.png)

**Comment by NsCDE** [comment]
Well, before that, did terminal with the setup script was running? Did you passed initial setup questions?
Maybe you are missing xterm. It is a strong depedency.

**Comment by espio999** [comment]
Hello again.

> did terminal with the setup script was running? Did you passed initial setup questions?

This is no problem.  I saw some questions after NsCDE splash screen at the 1st rebooting just after installation process.  Screenshot attached is the one just after all questions.

**Comment by espio999** [comment]
Hello again.

> Well, before that, did terminal with the setup script was running? Did you passed initial setup questions? Maybe you are missing xterm. It is a strong depedency ... apt install xterm.

This is no problem.  I saw some questions after NsCDE splash screen at the 1st rebooting just after installation process.  Screenshot attached is the one just after all questions.

**Comment by NsCDE** [comment]
Hello @espio999 

Then simply do what the text at the end of the setup said:

"Please select a color palette (default: Broica) and GUI widgets integrations"
"that you want to apply and confirm with OK in Color Style Manager"
"Logout and login again for the full changes to take effect."

In other words, choose color scheme in Color Style Manager (see your screenshot above)
and press "OK", or simply press "OK" for default color scheme.

**Comment by espio999** [comment]
Hi

Thank you for your support.  Everything is ok for now.

Japanese input/output is also ok.
Although some window titles render it as block, it can resolve in "Style Manager - Font".

![](https://cdn-ak.f.st-hatena.com/images/fotolife/e/espio999/20211230/20211230211135.png)

**Comment by NsCDE** [comment]
Ok, nice. Try to do some X11 resolution change ("xrandr -s 1920x1080" for example), 1024x768 is not much of the experience. Find some font which has more complete UTF-8 set for your language, and you should be fine.

May we close this issue?

**Comment by espio999** [comment]
> May we close this issue?

Yes, please.
I appreciate for your support.
