### ISSUE TITLE
variable missing?

### ISSUE THREAD

**Issue by christian-moerz** [NsCDE/NsCDE#87]
I'm working on the FreeBSD port for version 2.0; while the new GNU autoconf setup certainly has simplified packaging a lot, I'm wondering whether I'm facing some packaging or upstream issues:

Starting nscde version 2 the first time runs the update script. All appears fine initially, but then I tried running the colors manager, changed the color profile and then the issues started: I realized that configure did not correctly detect python, causing all python scripts to end up with a "!#:" shebang. That one I managed to work around.

Now, having fixed that, I'm getting messages like these:
[StyleMgr][Key]: No such key: Help[ColorMgr][Key]: No such key: HelpTraceback (most recent call last):
  File "/usr/local/libexec/NsCDE/palette_colorgen", line 792, in <module>
    main()
  File "/usr/local/libexec/NsCDE/palette_colorgen", line 772, in main
    ncolors = int(a)
ValueError: invalid literal for int() with base 10: '$[NSCDE_PALETTE_NCOLORS]'
[PImageLoadSvg]: Tried to load SVG file when FVWM has not been compiled with SVG support.
[ColorMgr][LoadIcon]: <<WARNING>> Unable to load pixmap /home/user/.NsCDE/tmp/_fullpalette.xpm

In case, this is a packaging issue (which I suspect) - can you tell me, where that variable needs to be set for this to work?
Appreciate your help.

**Comment by NsCDE** [comment]
Hi @christian-moerz 

Situation with python 3 detection on FreeBSD is a LOT more simple when meta package python3-3_3 is installed to provide same sane symlink to the actual Python installed on the system:

# pkg which /usr/local/bin/python3
/usr/local/bin/python3 was installed by package python3-3_3

... then configure will work for Python.

For the rest of your problems:

ast-ksh must be installed on the system, not some clone. Shebang for it should look like this: "#!/usr/local/bin/ksh93" in generated scripts after ./configure.

Next, error from palette_colorgen - check if it is using python 3, not python 2. Then, please tell me the version of the fvwm on which you are running this. In my Qemu/KVM VM with FreeBSD it is "fvwm-2.6.9_2" from the output of "pkg info | grep fvwm". FTR, NsCDE runs ok on my FreeBSD with setup described above.

P. S.
If you need to further check for dependencies, please see pkg/debian/control, pkg/rpm/NsCDE.spec and pkg/pacman/PKGBUILD in source tree. You will get idea what package name equivalents and ports are needed on FreeBSD.

**Comment by christian-moerz** [comment]
I traced my issue back to a screwed up ~/.NsCDE directory. My initial run had those broken shebangs and likely broke everything.

After a reset to the original 1.4 config dir and rerunning migration, it seems to work on the surface. However, things are still kind of strange. I.e. I can't start the "Watch errors" application - clicking on the icon does nothing for me; in the color profiles, when I click on some entry in the list view, I now get strange error messages:

sh: environment corrupt; missing value for àRÍ
sh: environment corrupt; missing value for àRÍ
sh: environment corrupt; missing value for àRÍ
sh: environment corrupt; missing value for àRÍ
sh: environment corrupt; missing value for àRÍ
sh: environment corrupt; missing value for @H
sh: environment corrupt; missing value for @H
sh: environment corrupt; missing value for @H
sh: environment corrupt; missing value for @H
sh: environment corrupt; missing value for @H
sh: environment corrupt; missing value for @H
sh: environment corrupt; missing value for @H
sh: environment corrupt; missing value for @H

values seem to differ once I switch between different color profiles.

I'm running on python 3.8, fvwm is stock from ports:

fvwm-2.6.9_2
Name           : fvwm
Version        : 2.6.9_2
Installed on   : Fri Jul 30 22:33:22 2021 CEST
Origin         : x11-wm/fvwm2
Architecture   : FreeBSD:12:amd64
Prefix         : /usr/local
Categories     : x11-wm
Licenses       : 
Maintainer     : cy@FreeBSD.org
WWW            : http://www.fvwm.org/
Comment        : Popular virtual window manager for X
Options        :
        BIDI           : off
        ICONS          : on
        ICONV          : on
        NLS            : on
        PNG            : on
        RPLAY          : off
        SESSION_MGMT   : on
        STROKE         : off
        SVG            : off
Shared Libs required:
        libXpm.so.4
        libXrender.so.1
        libreadline.so.8
        libfreetype.so.6
        libXcursor.so.1
        libICE.so.6
        libXft.so.2
        libXext.so.6
        libpng16.so.16
        libintl.so.8
        libSM.so.6
        libiconv.so.2
        libfontconfig.so.1
        libXinerama.so.1
        libX11.so.6
Annotations    :
        FreeBSD_version: 1202000
        repo_type      : binary
        repository     : FreeBSD

It seems that those shell errors are not affecting the overall operation otherwise. I should probably point out that I do have ksh93 installed; not sure where the bourne shell calls are coming from.

**Comment by christian-moerz** [comment]
I've retried with a blank user profile starting from scratch. Unfortunately no difference.

Attempting to launch the watch errors window manually produces:
user@bsd:~ % FvwmCommand -i 1 f_ToggleFvwmFunc WatchWinMgrErrors Raise f_WatchErrors > error.txt
0x0240000c window               Watch Errors
0x0240000c icon                 Watch Errors
0x0240000c icon file            NsCDE/DtErrors.l.pm
0x0240000c mini icon            width 24, height 37, depth 0
0x0240000c class                XTerm
0x0240000c resource             WatchWinMgrErrors

[fvwm][__execute_function]: <<ERROR>> No such command 'WatchWinMgrErrors'

Also interesting side effect from starting from scratch: clicking on the file manager icon directly in the bar works; if I open the attached menu on the top and click File Manager, it doesn't work.

Starting first with xterm and then manually launching nscde to get to the console errors, I'm getting more error messages during launch of a terminal application:
[fvwm][__execute_function]: <<ERROR>> No such command 'xfce4-terminal'
[fvwm][__execute_function]: <<ERROR>> No such command 'e'
[fvwm][__execute_function]: <<ERROR>> No such command 'top'

I'm surprised that it attempts to start three applications instead of just the terminal application, which then does not open; xfce4-terminal is installed and can be launched manually via xterm, though...

**Comment by NsCDE** [comment]
There is most probably more then one thing wrong in your setup.

First of all, it looks like ExecUseShell in /usr/local/share/NsCDE/fvwm/Main.fvwmconf points to non-existent, wrong or empty value. This is most certailnly a source of this __execute_function <> no such command errors. It should point to
"/usr/local/bin/ksh93" on FreeBSD. Check it.

Next, this "sh: environment corrupt; missing value for àRÍ" are errors from FreeBSD shell or even C library and points to some error inside environment. Probably related to LC_ and LANG variables. Most probably this screw up autoconf, profile migration and who knows what else. I saw this situation on FreeBSD (and only on FreeBSD) couple of times and never figured out what it is, and the logout from X and reboot made this corruption dissapear. Not a NsCDE nor FVWM problem, but it can affect processes.

The best thing for you should be to logout, reboot, run some other WM or from the console re-configure and re-make NsCDE 2.0 and reinstall, having in mind that you check ExecUseShell in the file described above, and that /usr/local/bin/python3 is in the shebang of the python scripts - see couple of files in nscde_tools/ directory for that, before running make install.

After the successful installation, unpack backup of your profile, and let the migration from 1.X do the job. Of course, under assumption you don't have this "environment corrupted" errors all around.

**Comment by christian-moerz** [comment]
Thanks for the pointers. Appreciate your help in troubleshooting.

I've attached the build process and the startup after migration.

[nscde-build.txt](https://github.com/NsCDE/NsCDE/files/7798034/nscde-build.txt)
[nscde-startup.txt](https://github.com/NsCDE/NsCDE/files/7798035/nscde-startup.txt)

Rebuilt and double checked the locale settings - they're all set to en_US.UTF-8; ExecuteUseShell points to /usr/local/bin/ksh93. 

After re-installation and changing my startup to dump output to a log file, I've gotten one warning/error that I'm wondering whether this might be an additional pointer to the underlying issue? 

Failed to connect to session manager: Failed to connect to the session manager: SESSION_MANAGER environment variable not defined

Is this something I need to set somewhere? I'd expect this to be set by fvwm?

The spurious sh messages are gone now. I'm getting this instead, when I try to start a terminal from the "fold up" menu over the terminal icon:
Failed to connect to session manager: Failed to connect to the session manager: SESSION_MANAGER environment variable not defined
[fvwm][__execute_function]: <<ERROR>> No such command 'xfce4-terminal'
FvwmCommandS: leaving a partially sent message in the queue

This looks to me, like my environment variables could be causing this?

**Comment by NsCDE** [comment]
Hi @christian-moerz 

1. You can ignore those about session manager. You can replace SessionManaged=true to false in /usr/local/share/xsessions/nscde.desktop to get away this message (something to rethink anyway).

2. When using FvwmCommand or nscde_fvwmclnt wrapper, you should quote FVWM directives with double quotes and escape '$' and similar, or quote with single quotes.

FvwmCommand 'f_ToggleFvwmFunc WatchWinMgrErrors Raise f_WatchErrors'

build log looks ok now, startup log complains something about unrecognized keys, which fvwm does not do on my setup in VM, but thats not related or imporant here.

You opened here couple of issues actually. Check if we got everything sorted out now. Thanks.

**Comment by NsCDE** [comment]
Hi @christian-moerz

If you are still playing with NsCDE, I think new autoconf should take care of python shebang correctly. If not, there is new configure option [1] where this can be changed. It was added here to work around NetBSD clunky alternatives system, but should be useful also in other cases.

```
  --with-python-shebang="STRING"
                          How to call Python 3 in python scripts (specified
                          WITHOUT hash and exclamation mark). This disables
                          python 3 autodetection and fully trusts what is
                          provided by the user. One example of this option can
                          be: "/usr/bin/env python3".
```
