### ISSUE TITLE
Web Browser not found

### ISSUE THREAD

**Issue by enigma131** [NsCDE/NsCDE#92]
I have followed #34 but still not solved.
I have add InfoStoreAdd browser firefox-esr in $HOME/.NsCDE/NsCDE.conf, restarted NsCDE but nothing.
In the tread linked, I have find on Debian systems the command is not :
ksh -x /opt/NsCDE/libexec/appfinder firefox-esr
but should be:
ksh -x /usr/lib/x86_64-linux-gnu/NsCDE/appfinder firefox-esr   that gives the correct output : 
+ [ xfirefox-esr '==' x ]
+ InfVarName=firefox-esr
+ [ x '==' x ]
+ echo NOARG
NOARG
+ exit 1
Is the non correct path related to the problem ?

**Comment by NsCDE** [comment]
Hi

Where did you find this "ksh -x /opt/NsCDE/libexec/appfinder firefox-esr" in the NsCDE? This does not exist.

Once set up variable for default apps is not read again on restart. You need either to log out and log in, or to avoid this, you can force what is written in ~/.NsCDE/NsCDE.conf manually:
```
nscde_fvwmclnt 'InfoStoreAdd browser firefox-esr'
```

**Comment by enigma131** [comment]
I have try both : 
nscde_fvwmclnt 'InfoStoreAdd browser firefox-esr'
or
InfoStoreAdd browser firefox-esr
logout, + login, same result in ~/.xsession-errors :

[fvwm][__execute_function]: <<ERROR>> No such command 'firefox-esr'

**Comment by NsCDE** [comment]
You are probably suffering from #88

Please fetch master from git, or download refreshed tarballs from te assets for 2.0, or appropriate package for your system if it is available, and try with that.

**Comment by enigma131** [comment]
Ah probably, i haven't compile but install both cde and nscde 2.0 (latests) from sparkylinux repos, prehaps not up to date.
Can i try to patch a script somewhere without compile ?

**Comment by NsCDE** [comment]
What system are you using? Linux distro, BSD ... ?

**Comment by enigma131** [comment]
Sparky linux minimal gui http://sourceforge.net/projects/sparkylinux/files/base/sparkylinux-6.1-x86_64-minimalgui.iso/download
then via terminal : sudo apt install nscde-desktop as writen by Sparky team

**Comment by NsCDE** [comment]
Deinstall nscde, get debian package from assets and install manually with apt install ./pkgname.

https://github.com/NsCDE/NsCDE/releases/download/2.0/nscde_2.0-9_amd64.deb

This contains fix. You can notify Sparky Linux maintainer to update too.

**Comment by enigma131** [comment]
Ok i will try . Whasn't Sparky version 2 also ?

**Comment by NsCDE** [comment]
Yes, but because #88 and some other annoying bug, I have updated source and my packages without releasing new version. It was around new year and only couple of days after I have released 2.0 without realizing this 2-3 stupid errors.

**Comment by enigma131** [comment]
same error :[fvwm][__execute_function]: <<ERROR>> No such command 'firefox-esr'
but i've just see a other error above : [fvwm][__execute_function]: <<ERROR>> No such command 'nscde_fvwmclnt'
and below : [fvwm][Echo]: NsCDE: Selected default for browser: firefox-esr   <--- this is ok
so in fact it didn't find nscde_fvwmclnt ... the last error report is not complete!

**Comment by NsCDE** [comment]
Do:

`rm -f ~/.NsCDE/Subpanels.fvwm?.fvwmgen`

Then open ANY subpanel, click left-and-only titlebar button to open context menu of subpanel and click "Reload Subpanel", then restart NsCDE from the Workspace menu or with System Action Dialog.

**Comment by enigma131** [comment]
Thanks, it's working !
I will inform sparkylinux .
Thanks for your prompt help!

**Comment by NsCDE** [comment]
Great.

2.1 should have more dynamic trigger to reload default variables and regenerate subpanels config.

**Comment by enigma131** [comment]
pavroo have reacted quickly, i will try tomorrow on VM : https://forum.sparkylinux.org/index.php/topic,5986.0.html
