### ISSUE TITLE
Is there an way to change the analog clock to digital?

### ISSUE THREAD

**Issue by Lixkote** [NsCDE/NsCDE#93]
Is there an way to change the analog clock in the bottom bar to digital?

**Comment by NsCDE** [comment]
Yes.

See section 8.1 of the manual for explanation and examples. You can use Window Maker's wmclock digital clock for example.
See also #20 for additional examples.

**Comment by Lixkote** [comment]
![Zrzut ekranu z 2022-01-21 17-07-13](https://user-images.githubusercontent.com/95425619/150560342-bbc5be86-c3b9-4dfc-a107-c92ba3d40d2e.png)
Thanks for help!

**Comment by ezvision** [comment]
> ![Zrzut ekranu z 2022-01-21 17-07-13](https://user-images.githubusercontent.com/95425619/150560342-bbc5be86-c3b9-4dfc-a107-c92ba3d40d2e.png) Thanks for help!

@Lixkote Hey man, I know you posted this a while ago but I was wondering if you would be able to help me out if you still remember. I have wmclock working but I'm not sure how to turn it into an applet. My understanding is that I have to change something in FrontPanel.actions but nothing I change here turns wmclock into an applet.
![image](https://github.com/NsCDE/NsCDE/assets/31146313/ceefd373-b95d-43e4-8d99-d7ebf2a60e44)
I would really appreciate if you could help me out with this.
