### ISSUE TITLE
Missing required header

### ISSUE THREAD

**Issue by sacarde** [NsCDE/NsCDE#96]
hi,
   I try to install nscde on my ubuntu-18.04, I install dependencies, and:

git clone --depth 1 https://github.com/NsCDE/NsCDE.git
cd NsCDE

but when I run: ./configure I have:
...
...
configure: error: Missing required header files.

https://paste.ubuntu.com/p/fk2V4DNYtv/

thank you

**Comment by NsCDE** [comment]
Hello,

This part of configure output is telling you all:

```
checking X11/xpm.h usability... no
checking X11/xpm.h presence... no
checking for X11/xpm.h... no
```

You are missing XPM library header files. On Ubuntu, probably `apt install libxpm-dev`.

P. S.
You can find ready made deb package in assets. It is compatible with Ubuntu.

**Comment by sacarde** [comment]
ok, installing libxpm-dev solves problem

thank you
