### ISSUE TITLE
can't omit workspaces/pages without ruining taskbar

### ISSUE THREAD

**Issue by dchmelik** [NsCDE/NsCDE#97]
I don't use workspaces (I prefer just using three large monitors) and don't know what workspace pages are, so want to disable all that.  When I did, it ruined the taskbar (re-enabling fixed it; ) there should be an option to omit workspaces/pages.

**Comment by NsCDE** [comment]
Rare case, but legal case I would say.

Workspaces (or desks in FVWM terminology) are what you see as One Two Three Four ... they are firther subdivided to FVWM pages (4 pages per workspace by default).

Pages may be disabled, while workspaces can only be reduced to two currently. If no workspaces are defined, then Workspace Manager in the middle of the Front Panel (what you call taskbar) cannot appear, ruining Front Panel geometry.

Currently, workspaceless and pageless setup is reserved for so called "sandbox mode". In this mode many aspects of the NsCDE are not enabled, but just window decorations and basic background. This is meant as Xephyr/Xnest configurations for isolated applications. No workspace menu, no Front Panel, no (almost) nothing ... not for general desktop.

For NsCDE 2.1 I will see if I can make Front Panel without WSM, there should be some additional calculations in FrontPanel.fvwmconfig for that, but it should be ok. In the meantime, you can use two workspaces setup. Combined with monitors, it may not hurt as additional space.

**Comment by NsCDE** [comment]
@dchmelik 

I have just commited in master the fix which enabled Front Panel to work without Worspaces Manager. Test looks good. I will close this one. Please feel free to reopen if you find it still not ok.
